### ISSUE TITLE
Add HTTP health probes to Kyma Environment Broker

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/compass#1001]
**Description**

We should add the liveness and readiness probes to KEB component to be able to push health statuses for high level availability monitoring.

Here is some draft PR done by @ksputo: https://github.com/kyma-incubator/compass/pull/750/files

**AC**
- we are able to call via HTTP the liveness and readiness probes

**Comment by mszostok** [comment]
My opinion about liveness and readiness probes:

#### Liveness

**Assumption:** Kubernetes uses liveness probes to know when to **restart** a container.

So liveness should detect all problems which makes a container is unresponsive, e.g. application is deadlocked due to a multi-threading defect—restarting the container can make the application more available, despite the defect. The configuration was wrong so restart can reload the newest changes e.g. from ConfigMap (in better scenario such ConfigMap should be watched and reload the config in runtime but this is more complex and mostly not implemented,  so restart and reload can help). So such case can be used to just do not wake up someone in the middle of the night to restart a container.

**Summary:** liveness should cover are necessary check which can fail and restart of container is necessary to help application to deal with that problem. (reloads, deadlocks etc). But e.g. checking some external dependencies e.g. if dependent service is responsible should not restart the container because it won't help. In such scenario the readiness should be used because how the restart of the app will help you when the external system is returning e.g. 429 (to many request). 



#### Readiness

**Assumption:** Kubernetes uses readiness probes to decide when the container is available for **accepting traffic.**

This check should be used when your service is performing well but currently cannot accept traffic because it started performing some batch task like cache sync, or maintainance 

**Summary:** readiness should be used when the application should not be restarted because application itself is performing well but the external traffic cannot be accepted because of some background work.

some example article about that: https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/


In case when the external dep are not available the IMO we should just use REST codes, e.g.:
- 503 -  Service Unavailable - simply indicates that the server is temporarily unable to handle the request, but that is functioning as normal otherwise. Request can be repeated by user


If you use the readiness probes then K8s will just remove you from the service load balancers and end user who will call e.g. KEB will  get 404 (Not Found) status code which can be misleading for the end user as the endpoint is correct, but we just not able to e.g. send request to director.

**Comment by polskikiel** [comment]
IMO 
Readiness: ping provisioner (if they provide status endpoint)
Liveness: ping database

**Comment by mszostok** [comment]
@polskikiel I cannot agree with you as I describe in previous comment:
> f you use the readiness probes then K8s will just remove you from the service load balancers and end user who will call e.g. KEB will get 404 (Not Found) status code which can be misleading for the end user as the endpoint is correct, but we just not able to e.g. send request to director, so we are probably temporary unavailable a user can repeat the request after some time.


Same for liveness. If you make a ping to database and this database will not `pong` then you will restart the container are you always sure that container restart will help? AFAIK In current behavior we have some retries when putting sth to database + step will be just marked as failed with transparent info to user. Restart of the container should be only then when we are sure that reloading the application will help.

**Comment by mszostok** [comment]
E.e.g we already have a good example of liveness check in Helm Broker. There we are performing check to validate if Helm Broker does not stuck and does not get notification from informer anymore. In such case we know that restart is helping. It not solving the root cause but at least it helping :)

**Comment by polskikiel** [comment]
Ok, I agree with you :)
