### ISSUE TITLE
Automatic status update for Application and Runtime entities

### ISSUE THREAD

**Issue by crabtree** [kyma-incubator/compass#1017]
**Description**

Status of Application and Runtime entities should be automatically set to `CONNECTED` when the given Application/Runtime communicates with the Director API. The communication can be direct or through the Integration System. Thanks to the tenant-mapping-handler the context of a request contains the required information.

In case the user will modify the status manually, it can be replaced by the automatically computed one.

**Reasons**

We need that feature to know if application or runtime is connected to compass. Without that functionality all entities are marked as INITIAL only.

**AC**

1. Status of Application and Runtime entities must be automatically set to `CONNECTED` when the given Application/Runtime communicates with the Director API. Regardless of the previous status.
**Example**:  Application register package (status: CONNECTED); Runtime ask for applications (status: CONNECTED)

2. If IntegrationSystem communicates with the Director API it manages status of Runtimes and Applications and automatic set to `CONNECTED` feature is disabled (must not happen).
**Example**: Integration System sets Application/Runtime status to "FAILED" (status: FAILED); IS register Application packages without status attriubute (status: stays as it was)

3. In case of User flow update, status is not set to `CONNECTED`, stays as it was. In case the user will modify the status manually, it can be replaced by the automatically computed one.
**Example**:  User creates Application or Runtime by hand (status: as user set); User set status to application definition managed by application (status: changed to user one, when external application will update application definition status changes to `CONNECTED`)

**Comment by PK85** [comment]
Check status:
1) :ok:
