### ISSUE TITLE
Custom Headers and Query Parameters cannot contain '-' character

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#1021]
**Description**

When registering Application to Director user can specify `AdditionalHeaders` and `AdditionalQueryParams` in `DefaultInstanceAuth`.
However, the header and query parameter names can not contain `-` character which in case of headers is quite common, for example, `Content-Type` header.

**Expected result**

Headers with `-` can be registered by Director API.

**Actual result**

Query structure is invalid and therefore rejected by the GraphQL server.

**Steps to reproduce**

Try to register Application with `AdditionalHeaders` that contain `-` like `Content-Type`.

**Troubleshooting**

**Ideas/Solutions**
- make `QueryParams` and `AdditionalHeaders` as JSON Object (String)

**AC**
After change
- adjust Connectivity Adapter
- adjust Agent

**Comment by PK85** [comment]
@kfurgol has checked that issue, and looks that we have design API issue here, as HTTPHeaders are a map in graphQL and that '-' character is not allowed. @crabtree @pkosiec how we can enable those chars here?

**Comment by akrausesap** [comment]
Unfortunately Qualtrics uses such a header: https://api.qualtrics.com/docs/api-key-authentication
