### ISSUE TITLE
Inconsistency in Director GraphQL API between input and types

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#104]
1. `DocumentInput` defines 2 fields, that are missing in the `Document`:
- displayName
- description

2. `APISpecInput` defines format as a required field, but `APISpec` defines it as an optional field. 
The same for `EventAPISpec`.

AC:
- fix inconsistency
- update integration tests to check if fields are properly populated

**Comment by dbadura** [comment]
@aszecowka 
Is in `APISpecInput` format required or optional? 
The same question for `EventAPISpec`
