### ISSUE TITLE
Director API cleanup - delete deprecated types, attributes, queries and mutations

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#1040]
**Description**
When we introduced api-packages, we marked for exampe App#APIDefinitions App#EventDefinitions as deprecated. 
We need to cleanup our API.

**Reason**
To avoid potential misuse we need to remove that deprecated API.

**AC**
- remove depracated Director API parts:
   - legacy API before Packages
   - legacy AutoScenarioAssignments API
   - other deprecated API if found

**Comment by pkosiec** [comment]
@kjaksik Please also see this issue: https://github.com/kyma-incubator/compass/issues/826
