### ISSUE TITLE
KEB should provide an option to remove a given component from installation CR

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/compass#1049]
**Description**

In current implementation KEB provides only an option to make a given component as optional. Right now we do not have a clear solution for just disabling some components from installer CR. Because of that in this PR we had to do some workaround which can be error prone: https://github.com/kyma-incubator/compass/pull/1012

**AC:**
- KEB allows specifying which components should be removed from installer CR and user is not able to request it installation. 
- Optional components still available under ServicePlan
  - check with modules owners if some of them are optional now, if not optional list will be empty
- ToNotInstall list of modules is an internal list used by KEB
- both lists configurable from yaml
- documentation updated

**Comment by PK85** [comment]
@mszostok we need to take into account to separte optional/toNotINstall list per plan. Could we already include that in that story as we plan to add trial plan in this relase as well?

**Comment by mszostok** [comment]
Hi, yes. IMO we can link together those two things. Here is the issue from Karol who wants to introduce skipping steps functionality: https://github.com/kyma-project/control-plane/pull/69/files

we need to take a look at this implementation and ensure that it will work in a generic way and can be also used in this task
