### ISSUE TITLE
Provisioner allows to install Kyma from pre-releases on DEV

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/compass#1052]
**Description**

Provisioner should by default enable an option on DEV environment to use Kyma from pre-releases. It's crucial for e2e testing before creating official release. 

This will be really easy to implement. Just allowing to specify 3rd parameter (currently hardocded `false`) by environment variable:
https://github.com/kyma-incubator/compass/blob/bcbc7b1d10d6ff19c13cfc8161c0567bb31deaf0/components/provisioner/cmd/main.go#L159

**Reason**
Doing that by manually uploading this pre-release to provisioner leads to errors not directly related with the created pre-release + extends time needed to create such runtime.  (We had that problem during 1.11  Kyma release)

**AC:**
- provisioner on dev allows creating Kyma from prereleases using official YAMLs

**Comment by Szymongib** [comment]
Resolved in #1062
