### ISSUE TITLE
Generate credentials while creating Runtime and Application

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#106]
**Description**
We need a place to store credentials that will be used by RuntimeAgent and then paired with compass via connector.

**AC**
- extend Application GraphQL type with field `auths` (array of auths from SystemAuths table). Implement resolver to get entries from SystemAuth table
- while generating OneTimeToken for Application, create new empty (ID + ref) entry in SystemAuths table. ID of the entry will be used as `auth_id`.
- Endpoint for generating OneTImeToken for application
  - while generating OneTimeToken for Runtime, create new empty (ID + ref) entry in SystemAuths. ID of the entry will be used as `auth_id`.
- Endpoint for generating OneTImeToken for runtime
  - Call for OneTimeToken endpoint in connector. (Ask frogs if they want one endpoint with duration parameter or stay with seperate endpoints for app and runtime).
- add integration tests for new mutation + auths field
- remove skip in e2e tests for system auth.
**Reasons**

We need to add `auths` field for Application, because we will use auth ID to resolve tenant in tenant mapping service. In future we want to support multiple authorization methods.

**Comment by pkosiec** [comment]
See https://github.com/kyma-incubator/compass/issues/91 - we need to consolidate the tasks into one.
