### ISSUE TITLE
De-provisioning of Resources from KEB

### ISSUE THREAD

**Issue by anishj0shi** [kyma-incubator/compass#1066]
After Provisioning of resources like LMS, azure event-hub, etc, 
if the user of KEB requests de-provisioning of a kyma-runtime, we need to ensure that all these other resources are cleaned up as well.

**Comment by piotrmiskiewicz** [comment]
we are working on deprovisioning steps, so it could be done there. see: https://github.com/kyma-incubator/compass/issues/733

**Comment by anishj0shi** [comment]
@piotrmiskiewicz #733 deals with deprovisioning of just runtime or all the other dependencies, like LMS and for our case event-hubs?
I reckon it will be a big task which includes the following:
1) Deprovisioning of runtime
2) Deletion of LMS tenant
3) Deletion of event-hub namespace (which is per runtime)

will it make sense to track all of it under this epic?

**Comment by piotrmiskiewicz** [comment]
the #733 is about providing steps "framework" for deprovisioning, then you will implement deprovisioning step for your domain like for provisioning.

**Comment by polskikiel** [comment]
The implementation of deprovisioning framework has been done in this PR: https://github.com/kyma-incubator/compass/pull/1055

From now you can create your own deprovisioning steps in KEB. You can follow the documentation, which is available [here](https://github.com/kyma-incubator/compass/pull/1111/files#diff-6ee455cdcbad6360368d116a0cfdedc3) until merge to master.
