### ISSUE TITLE
Implement fetch request for package/ApiDefinition

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#107]
**Description**
In our API we have two ways how Application would provide API specifications. That story is about implementing a way with fetching them from URLs.

**Reason**
Many solution uses already that way of registering specs with metadata-service.

**AC**
- implement fetch request for APISpec for SINGLE file mode only 
  - PACKAGE, INDEX not supported
- when fetched then data:CLOB must be set as well
- update fetchRequest triggers specification fetching and status update
- client could ask to refetch anytime
- errors must be logged
- add integration test
- enhance Connectivity Adapter to make of use of that feature

**Out of scope**
- provide retry mechanism 
- auth support
- EventDefinition, Documentation objects

**Example**
1. Example fetchRequest:
```
                        "fetchRequest": {
                          "url": "https://domain/abs/api-docs",
                          "auth": null,
                          "mode": "SINGLE",
                          "filter": null,
                          "status": {
                            "condition": "INITIAL",
                            "timestamp": "2020-03-27T21:29:41Z"
                          }
                        }
```
2. If auth, filter attributes provided then must be persisted under fetchRequest but not used.
3. Status flow: INITIAL then SUCCEEDED or FAILED. When client updates fetchRequest status is updated. 
4. Add integration test that points to specification from github.

**Comment by crabtree** [comment]
After a short review of the task we can distinguish here two components that can be implemented under separate issues:
- goroutine handling the fetch requests
- the component that handles the auth for the fetch requests

**Comment by pkosiec** [comment]
As discussed, in first implementation we will go with synchronous approach, due to limited time.
- Remove UNUSED in FetchRequestStatus enum

**Comment by PK85** [comment]
When finished, please check and close: https://github.tools.sap/kyma/backlog/issues/301
