### ISSUE TITLE
Metrics for Compass components

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#1071]
**Description**

- Define requirements for metrics collections. Some ideas:
    - CPU / Memory consumption
    - active DB connections number in connection pool
    - avarage time of GraphQL request handling
    - active goroutines
- Collect metrics for all Compass components:
   - Director
   - Connector
   - Gateway
   - Provisioner
   - KEB

**Reasons**

Proper monitoring setup for all components is crucial to maintain stable production environment.

**Comment by janmedrek** [comment]
Provisioner metrics issue: https://github.com/kyma-incubator/compass/issues/1385
