### ISSUE TITLE
Refer one list of regions for Azure Plans

### ISSUE THREAD

**Issue by anishj0shi** [kyma-incubator/compass#1076]
We maintain one list of regions for azure here:
https://github.com/kyma-incubator/compass/pull/1006/files#diff-93a4089093a70c6af5ff0c19cccfc02cR50

Can we use this in the broker's plan schema. over here: 
https://github.com/kyma-incubator/compass/blob/master/components/kyma-environment-broker/internal/broker/plans.go?

with this we maintain a common list of azure regions which are encapsulated in an azure package (so semantically, it makes sense) and in future if we want to use any other azure related APIs we can reuse the location list from here.

**Comment by anishj0shi** [comment]
i think, this is fixed by: https://github.com/kyma-incubator/compass/pull/1006

**Comment by PK85** [comment]
@anishj0shi closing that as you found it's already resolved.
