### ISSUE TITLE
Implement integration tests for AutomaticScenarioAssignments

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#1082]
**Description**

Implement integration tests for all AutomaticScenarioAssignments mutations and queries:

```graphql
type Mutation {
    setAutomaticScenarioAssignment(in: AutomaticScenarioAssignmentCreateInput): AutomaticScenarioAssignment!
    deleteAutomaticScenarioAssignmentForScenario(scenarioName: String!): AutomaticScenarioAssignment!
    deleteAutomaticScenarioAssignmentForSelector(selector: LabelInput!): [AutomaticScenarioAssignment!]!
}

type Query {
    automaticScenarioAssignmentForScenario(scenarioName: String!): AutomaticScenarioAssignment
    automaticScenarioAssignmentForSelector(selector: LabelInput!): [AutomaticScenarioAssignment!]!
    automaticScenarioAssignments(first: Int = 100, after: PageCursor): AutomaticScenarioAssignmentPage!
}
```

Make sure every time you query all fields from AutomaticScenarioAssignment.

**Comment by tgorgol** [comment]
[WIP]
Test scenarios to be covered:
**Scenario gets assigned to existing and newly created Runtimes**
1. Create Runtime 1 with Selector Label
2. Create new Automatic Scenario Assignment
3. Create Runtime 2 with Selector Label
4. Create Runtime 3 without Selector Label
5. Add Selector Label to Runtime 3
6. Query all Runtimes and check if they're assigned to the Scenario

**Runtime's Scenario gets modified when Automatic Scenario Assignment is edited**

**Runtime's Scenario gets removed when Automatic Scenario Assignment is deleted**

**Scenario added by Automatic Scenario Assignment stays assigned to Runtime even after manually removing `scenarios` Label from it**

**Trying to modify `scenarios` Label Definition by deleting a Scenario that's in use by any Automatic Scenario Assignment results in error**

**Comment by tgorgol** [comment]
Integration tests will cover only basic CRUD operations. Other cases will be covered by unit tests.
