### ISSUE TITLE
Connectivity-adapter and compass-director-gateway-integration keep on failing on postmaster

### ISSUE THREAD

**Issue by aerfio** [kyma-incubator/compass#1083]
**Description**
`Connectivity-adapter` and `compass-director-gateway-integration` keep on failing together on `post-master-compass-integration`. Logs in comments

Probably connected with https://github.com/kyma-incubator/compass/issues/1048

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1242847596645453825

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1242376493670076416

**Comment by aerfio** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1242056888049209344

**Comment by pkosiec** [comment]
Our API test (`compass-director-api`) passed. It calls Director directly.

This may be related to some components between integration tests and Director: Oathkeeper? Gateway?

The truth is that in both failing tests we don’t wait for ORY & gateway to be up. I can create an issue for that. We need to investigate it further, before putting Oathkeeper to blame 😛

**Comment by PK85** [comment]
Timeboxed to 3SP
