### ISSUE TITLE
Director has no proper readiness and liveness probes configured

### ISSUE THREAD

**Issue by franpog859** [kyma-incubator/compass#1091]
**Description**

Sometimes the tests connected to the Director (connectivity-adapter tests and compass-director-gateway-integration tests) are failing

<details>
<summary>See the error logs</summary>

```json
{
   "code":500,
   "error":"Failed to get application from Director: Post http://compass-director.compass-system.svc.cluster.local:3000/graphql: context deadline exceeded"
}
```
```json
{
   "code":500,
   "error":"Failed to get application from Director: Post http://compass-director.compass-system.svc.cluster.local:3000/graphql: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
}
```
```
Post https://compass-gateway.kyma.local/director/graphql: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

</details>

There is already [an issue to add reties to the Connectivity Adapter tests](https://github.com/kyma-incubator/compass/issues/1048) but this may not solve the problem

Today I came across the same problem on my cluster (it's alive for 2 days already). I wanted to provision a runtime but I've got the same error as the one mentioned earlier. It seems that Director doesn't respond at all

<details>
<summary>See the troubleshooting logs</summary>

The error I got from the Provisioner
```
Failed to register Runtime: Failed to register runtime in Director. Request failed: Failed to execute GraphQL query with Director: Post https://compass-gateway-auth-oauth.fran-custom-components-7.frame-frosh.ga/director/graphql: context deadline exceeded
```

The Provisioner logs
```
time="2020-03-27T09:55:15Z" level=info msg="Registering Runtime on Director service"
time="2020-03-27T09:55:45Z" level=info msg=">> variables: map[]"
time="2020-03-27T09:55:45Z" level=info msg=">> query: mutation {\n\tresult: registerRuntime(in: {\n\t\tname: \"runtimename34\",\n\t\tdescription: \"runtimedescription\",\n\t\tlabels: {\n\t\t\tscenarios: [\"DEFAULT\"],\n\t},\n\t}) { id } }"
time="2020-03-27T09:55:45Z" level=info msg=">> headers: map[Accept:[application/json; charset=utf-8] Authorization:[Bearer aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaa] Content-Type:[application/json; charset=utf-8] Tenant:[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa]]"
time="2020-03-27T09:55:45Z" level=error msg="Failed to provision Runtime runtimename34: Failed to register Runtime: Failed to register runtime in Director. Request failed: Failed to execute GraphQL query with Director: Post https://compass-gateway-auth-oauth.aaaaaaaaaaaa.aaaaaaaaaaaa.ga/director/graphql: context deadline exceeded"
```

It keeps failing more than once

Director logs
```
time="2020-03-27T09:59:09Z" level=warning msg="transaction rolled back" func="github.com/kyma-incubator/compass/components/director/pkg/persistence.(*db).RollbackUnlessCommited" file="/go/src/github.com/kyma-incubator/compass/components/director/pkg/persistence/persistence.go:54"
time="2020-03-27T09:59:09Z" level=warning msg="transaction rolled back" func="github.com/kyma-incubator/compass/components/director/pkg/persistence.(*db).RollbackUnlessCommited" file="/go/src/github.com/kyma-incubator/compass/components/director/pkg/persistence/persistence.go:54"
time="2020-03-27T09:59:31Z" level=info msg="Successfully reloaded scopes configuration" func=main.createAndRunScopeConfigProvider.func1 file="/go/src/github.com/kyma-incubator/compass/components/director/cmd/director/main.go:191"
time="2020-03-27T09:59:39Z" level=warning msg="transaction rolled back" func="github.com/kyma-incubator/compass/components/director/pkg/persistence.(*db).RollbackUnlessCommited" file="/go/src/github.com/kyma-incubator/compass/components/director/pkg/persistence/persistence.go:54"
```

Sidecars configuration seems to be ok though

Gateway logs
```
2020/03/27 09:58:39 http: proxy error: while rount trip the request: context canceled
2020/03/27 09:59:09 http: proxy error: while rount trip the request: context canceled
2020/03/27 09:59:39 http: proxy error: while rount trip the request: context canceled
2020/03/27 09:59:39 http: proxy error: while rount trip the request: context canceled
```

</details>

@Szymongib said that he sometimes gets the same issue with the Director on long-lasting clusters and restarting it solves the problem. Earlier in the chat, we established that the Director doesn't have a proper readiness probe

We think adding a correct liveness probe could be some **workaround** as it would restart the Director automatically. **Director should not require the restart** though

**Expected result**

- Director has a proper readiness and liveness probes configured
- Director doesn't require restarts (the potential bug is eliminated)

**Comment by pkosiec** [comment]
Thanks @franpog859!

Yes, your investigation will help - from logs it seems clear to me that the Gateway forwards the request, which means it's not the OathKeeper fault.

> @Szymongib said that he sometimes gets the same issue with the Director on long-lasting clusters and restarting it solves the problem

Hmm, but AFAIK the problem resulted in `connection reset by peer` error. I think it may be different, but anyway it may be related to DB connection of Director.

Anyway, we need to investigate it. This issue is similar: https://github.com/kyma-incubator/compass/issues/1083 and apart from proper readiness and liveness probes it would be great to find the root cause of this problem.

**Comment by PK85** [comment]
Estimation set to 0, as we have duplicated ticket timeboxed to 3SP.
