### ISSUE TITLE
Flaky Provisioner unit tests due to etcd timeout

### ISSUE THREAD

**Issue by franpog859** [kyma-incubator/compass#1101]
**Description** and **Actual result**

`post-compass-components-provisioner` job fails sometimes (for example [there](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-compass-components-provisioner/1243462778564382721)) with this error:

```
level=error msg="Failed to setup test environment: Failed to start test environment: failed to start the controlplane. retried 5 times: timeout waiting for process etcd to start"
```

It could be problematic because if the job failed the master image is not created and we cannot bump the Kyma charts with the actual image

It's a problem not only with this job but also with all tests running with the go test library

**Expected result**

Unit tests are not flaky

**Steps to reproduce**

The error occurs randomly so you can just rerun Provisioner unit tests

**Troubleshooting**

There could be an option to increase the timeout value. The investigation should be done in this filed

**Comment by janmedrek** [comment]
Moving to the KCP repo: https://github.com/kyma-project/control-plane/issues/87
