### ISSUE TITLE
Insecure SQL queries in Director

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#1103]
**Description**

Currently DB queries in Director are insecured, as they are built with `fmt.Sprintf` and string builder.
We need to convert them all to parametrized queries.

Most of them are located in `repo` helpers, but we also have custom queries like in applications for runtime query or `apiruntimeauth` domain.

Our findings:
- Create in `repo` is safe
- List has `additionalConditions` parameter (which is string)
- Conditions mechanism in `repo` helpers is unsafe.

**Comment by pkosiec** [comment]
I went through all repositories in Director. These are my findings.


## No issues

- all custom DB queries in repositories - user input is escaped with pq.QuoteLiteral.
- Filtering in list:
`components/director/internal/domain/label/query.go` - user input is escaped with pq.QuoteLiteral ("github.com/lib/pq")
- repo: Creator, Upserter, Updater use jmoiron/sqlx package which use parametrized queries
- repo: ExistQuerier, Deleter, Getter use parametrized queries


## To improve:
repo/common.go - GetQueryPart(idx int)  -> 
quote values for IN operation - DONE in PR: https://github.com/kyma-incubator/compass/pull/1187

repo/list.go + repo/list_pageable - additionalConditions is string, where is no quoting by default; this is the problematic function: `buildSelectStatement` from `common.go`

**Comment by kfurgol** [comment]
I've come to the same conclusion as @pkosiec, nothing to add from my side.
