### ISSUE TITLE
Provisioner is unable to deprovision runtime

### ISSUE THREAD

**Issue by ksputo** [kyma-incubator/compass#1123]
**Description**
When trying to deprovision runtime via KEB, it fails with error from provisioner:
```
time="2020-04-02T13:36:07Z" level=error msg="Failed to deprovision Runtime 848b4c49-dff4-4d52-9160-76852adbbd9b: Failed to get cluster: Cannot find Kyma config for runtimeID: 848b4c49-dff4-4d52-9160-76852adbbd9b"
```
The same thing happens when trying to call Provisioner directly via graphql playground - ends with error:
```
{
  "errors": [
    {
      "message": "Failed to get cluster: Cannot find Kyma config for runtimeID: 848b4c49-dff4-4d52-9160-76852adbbd9b",
      "path": [
        "deprovisionRuntime"
      ]
    }
  ],
  "data": null
}
```

However, there is a record in provisioner's database for given ID when checking with
```
select * from kyma_config where cluster_id='848b4c49-dff4-4d52-9160-76852adbbd9b'
```

This particular runtime was created on 01.04 and failed on installation (don't know yet if this is connected)

**Expected result**
Deprovisioning call to provisioner triggers runtime deletion on Gardener.

**Actual result**
The runtime is not deleted from Gardener or the database. 

**Steps to reproduce**
1. Provision a Kyma runtime (or use existing one)
2. Send deprovision call to Provisioner (via KEB or directly to Provisioner)

**Troubleshooting**

**Comment by janmedrek** [comment]
Solved in: https://github.com/kyma-incubator/compass/issues/349
