### ISSUE TITLE
Remove backup and backup-init component from kyma runtime

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-incubator/compass#1130]
As a different strategy for backup/restore gets applied (https://github.com/kyma-project/kyma/issues/7858), the kyma backup component gets no used. To reduce complexity, we should remove the components from the runtime configuration.

Please do not forget to remove the related backup-init component as well.

**Comment by suleymanakbas91** [comment]
Looks good to me

**Comment by a-thaler** [comment]
What is with https://github.com/kyma-incubator/compass/pull/1131/files#r403035694?

**Comment by rakesh-garimella** [comment]
Taken care of the comment via: https://github.com/kyma-incubator/compass/pull/1171
