### ISSUE TITLE
Fine tune naming validation for resourcegroup/event hubs

### ISSUE THREAD

**Issue by sayanh** [kyma-incubator/compass#1136]
**Description**

Right now, the length of the cluster has a minimum length validation. The name of the cluster is used to create Resource groups and Event hubs.
 The rules are as follows:
`Eventhub` related naming rules -> https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsofteventhub
`Resourcegroup` naming rules -> https://docs.microsoft.com/bs-latn-ba/rest/api/resources/deployments/validate#uri-parameters

**Reasons**

If naming validation fails in KEB, the asynchronous step of event-hub creation fails. Once failed, it goes for a retry which never succeeds. This is not a great experience. The validation check should happen right at the beginning and fail fast before even starting the async processes.

**Comment by marcobebway** [comment]
Blocked until we decide on the naming.
