### ISSUE TITLE
Call to Director with host header including 443 port always replies with 404 status code

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#1165]
**Description**

Call to Director with host header including 443 port always replies with 404 status code.

**Expected result**

Return proper result.

**Actual result**

Always 404 status code.

**Steps to reproduce**

Add header: 
- key: host 
- value: host:443

**Place to start investigation**
I think we need to adjust https://github.com/kyma-incubator/compass/blob/master/chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
configuration to use some regex to allow (if provided) port 443

**Comment by PK85** [comment]
@tgorgol I see STAGE env has a change but still 404. Please take a look.

**Comment by tgorgol** [comment]
I checked all envs and it seems to be working as expected.
