### ISSUE TITLE
Audit Logs for Compass Connector

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#1180]
**Description**

There is a mechanism for handling Audit Logs in Compass Gateway:
https://github.com/kyma-incubator/compass/blob/master/components/gateway/pkg/proxy/transport.go

In order to integrate Connector with it, we need to provide a proper transport function that would send logs to the configured audit log service. Director's implementation is extracting claims from included JWT token, we would need to fetch information on SystemAuthID from included client's certificate.

The exemplary implementation for Compass Director: https://github.com/kyma-incubator/compass/blob/master/components/gateway/pkg/proxy/transport.go

Default transport that is currently used: https://github.com/kyma-incubator/compass/blob/b544d2e565396c357310040169ac6abff57e8324/components/gateway/cmd/main.go#L57

**Comment by pkosiec** [comment]
Please remember also about routing Connectivity Adapter calls through Gateway - similarly what I did: https://github.com/kyma-project/kyma/pull/8029
I didn't change the routing for connector part, as it has to be tested to make sure everything works correctly.

**Comment by janmedrek** [comment]
A possible approach is to use additional mutators for Connector (just like in `Director-with-certs` scenario):
- TenantMappingHandler
-  IdToken

This will enable the use of the Director's current transport reducing implementation on our side. This needs to be tested though...
