### ISSUE TITLE
Investigate compatibility with Kyma's Headless CMS component

### ISSUE THREAD

**Issue by tgorgol** [kyma-incubator/compass#12]
As we discussed, we want our agent to be able to create Kubernetes' custom resources that will be consumed directly by Kyma's Headless CMS component. We don't want to rely on existing application-registry component to avoid having two registries in Kyma at the same time.

We should decide which Headless CMS features we want to support. For example:
1. Do we want to support multiple source types (`single`, `package`, `index`)? At the moment, application-registry component in Kyma supports only single files.
2. If we want to support packages, do we also want to support filtering by regex?
3. Which `DocsTopic` properties do we want to keep in our schema (`displayName`, `description`)?

Current definition of `DocsTopic` custom resource, that is consumed by Headless CMS can be found [here](https://github.com/kyma-project/kyma/blob/df58d5ba13fb350fae0faf963eb21b5603ee0c68/components/cms-controller-manager/config/crds/cms_v1alpha1_docstopic.yaml) and [here](https://kyma-project.io/docs/components/headless-cms/#custom-resource-docstopic-sample-custom-resource) is the documentation and example of said custom resource.

**Comment by PK85** [comment]
@tgorgol about:
*1. Do we want to support multiple source types (`single`, `package`, `index`)? Current application registry supports only single files.*

What do we support with Director API right now?

**Comment by tgorgol** [comment]
@PK85 
> What do we support with Director API right now? Cause I understand you have compared to metadata API.

At the moment, Director API supports all mentioned source types as well as filtering packages. When talking about application registry I meant the existing `application-registry` component, running in Kyma.

**Comment by PK85** [comment]
ok, closing issue as above requirements were added to API in #2
