### ISSUE TITLE
Test for KEB are executed twice

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/compass#1223]
Currently, on our pipeline test for KEB are executed twice. 

Example logs: https://storage.googleapis.com/kyma-prow-logs/logs/post-compass-components-kyma-environment-broker/1253074156648402944/build-log.txt

As a result we need to wait more time for the pipeline before merging our functionality, and when waiting for release image from master branch.

Additionally:
- we do not have an option to run unit-test locally using `make` command
- we do not have check for validating best practices, e.g. `errcheck`, `go vet`, `golint` etc. (consider enabling golangci-lint)

**AC**
-  same test on pipeline are executed only once
- we have an option to execute unit test locally using make command
- we have enabled minimum the `errcheck` and `go vet`

**Comment by polskikiel** [comment]
I fixed this issue
