### ISSUE TITLE
MVP monitoring on Director

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#1235]
**Description**
This issue is about to:
- define metrics that Director will expose
- show Director metrics dashoard in the MPS grafana 

**Reasons**

We're blind right now.

**AC**
- expose technical metrics:
  - [x] CPU / Memory consumption @pkosiec 
  - [x] active goroutines @pkosiec
  - [x] active DB connections number in connection pool @pkosiec
  - [x] response status codes from CIS Eventing (check if we could use k8s job status code) - Tenant Fetcher job monitoring? @pkosiec 
  - [x] response status codes from Ory Hydra  @pkosiec
  - [x] average time of GraphQL request handling @pkosiec
  - [ ] ~average time of DB request handling @kfurgol~ it would require additional plugin, that's why the AC is dropped.
- expose business metrics: @kfurgol - https://github.com/helm/charts/tree/master/stable/prometheus-postgres-exporter
  - [x] number of tenants
  - [x] number of applications
  - [x] number of runtimes
  - [x] number of tenants that have at least one application or runtime
At the end:
- [x] Sync charts in both places: compass/kyma repos
- [x] Add overrides to our clusters (`monitoring.pushgateway.enabled: true`) @pkosiec

**Comment by PK85** [comment]
When we will work on Gateway component then:
  - response status codes from Audit Log Service 
  - response status codes from Director

**Comment by pkosiec** [comment]
For business metrics we will use https://github.com/helm/charts/tree/master/stable/prometheus-postgres-exporter, as they have to be done directly on DB.
