### ISSUE TITLE
MVP monitoring on KEB

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#1236]
**Description**
This issue is about to:
- define metrics that KEB will expose
- show KEB metrics dashoard in the MPS grafana 
- will be an input for configuring alerting

**Reasons**

We're blind right now.

**AC**
- expose technical metrics:
  - CPU / Memory consumption
  - active goroutines
  - active DB connections number in connection pool
  - avarage time of provisioning
- expose business metrics:
  - number of service instances
    - status of provisioning
    - status of deprovisioning
  - status from all steps per service instance
    - provisioning sucess/failure 
    - deprovisioning sucess/failure

**Comment by piotrmiskiewicz** [comment]
I'd add:
 - how long does it take to provision instance (per provider: gcp, azure)

**Comment by ebensom** [comment]
I'd add theses metrics, whoich would be used for alerting:

- `keb_provisioning_result{runtime=, operation_id=,...}` : 0 if failed, 1 if successful, 2 if in progress
- `keb_provisioning_step_result{runtime=xx,operation_id=,step_name=,} ` : `0` if failed, `1` if successful, `2` if in progress

The same metrics for deprovisioning.

**Comment by ebensom** [comment]
@mszostok Quick question, do you plan to expose HAP usage metrics also?
