### ISSUE TITLE
Error while doing operation for non-existing tenant is enigmatic

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#1287]
**Description**
Scope extended, as we want to handle all cases!! 

When calling Director GraphQL API with non-existing tenant, returner error is highly confusing.

**Expected result**

Error, which says that the given tenant doesn't exist

**Actual result**

For example, here's the log for the error during creating Runtime:
```
graphql: while creating Runtime: while inserting row to 'public.runtimes' table: pq: invalid input syntax for uuid: \"\""
```
**Steps to reproduce**

Do any GraphQL operation for Director, while passing non-existing tenant.

**AC**
We need to support below cases:
- external tenant provided but internal one doesnt exist -> meesage: "Tenant not found."
- external tenant not provided and internal one doesnt exist -> message: "Tenant is required."
- external tenant not provided and internal one exist -> Case (Application/Rutime creds where external tenant is optional). Still must work as before.

@kjaksik Make sure we pass external tenant metainformation to Director, via JWT (ID token mutator).

**Comment by PK85** [comment]
Scope extended. We need to support below cases:
- external tenant provided but internal one doesnt exist -> meesage: "Tenant not found."
- external tenant not provided and internal one doesnt exist -> message: "Tenant is required."
- external tenant not provided and internal one exist -> Case (Application/Rutime creds where external tenant is optional). Still must work as before.
