### ISSUE TITLE
Request timeouts when processing with rich body in the Director

### ISSUE THREAD

**Issue by crabtree** [kyma-incubator/compass#1289]
**Description**

In case the Director API needs to process the request with multiple mutations (for example creation of multiple APIs in one request) it happens that the connection is terminated and the client receives the timeout error. This should be investigated and maybe we can increase the timeout parameter, but first, we need to detect on which component the connection timeouts.

**Comment by PK85** [comment]
Timeboxed: 3SP

**Comment by crabtree** [comment]
I did some short investigation and it looks like the problem is no longer valid. I tried to create multiple entities calling single GraphQL request with multiple mutations and the data was stored in the database.
