### ISSUE TITLE
Handle Name conflict when creating Azure EventHub Namespace

### ISSUE THREAD

**Issue by nachtmaar** [kyma-incubator/compass#1299]
**Description**
Follow up of https://github.com/kyma-incubator/compass/issues/1136

Azure EventHub Namespaces name have to be unique. In issue https://github.com/kyma-incubator/compass/issues/1136 we lowered the likelihood of a name collision by using a uuid instead of a user supplied name. 
However,  there is still a chance of a name collision.
We should handle that edge case properly.

**Reasons**

**Attachments**

https://github.com/kyma-incubator/compass/issues/1136

**Comment by marcobebway** [comment]
We decided to use the InstanceID instead of generating UUID (see: https://github.com/kyma-incubator/compass/pull/1304).

**Comment by raypinto** [comment]
We dont have azure eventhub anymore!
