### ISSUE TITLE
Refactor internal folders in KEB

### ISSUE THREAD

**Issue by sayanh** [kyma-incubator/compass#1303]
**Description**

It is found that the subfolders inside `components/kyma-environment-broker/internal/director` are duplicated in `tests/e2e/provisioning/internal/director`. Later it was found that the gardener, hyperscaler etc. are also needed in e2e provisioning test. Hence more code duplication.

The objective is to analyze the reasoning behind `internal` and refactor it to something common which can be reused in other components. 

**Reasons**

Code duplication.

**Comment by ksputo** [comment]
Resolved from gophers' perspective in KEB: [control-plane/#204](https://github.com/kyma-project/control-plane/pull/204)

Follow-up: [control-plane/#216](https://github.com/kyma-project/control-plane/issues/216)
