### ISSUE TITLE
False positive e2e-provisioning test

### ISSUE THREAD

**Issue by polskikiel** [kyma-incubator/compass#1314]
**Description**

It appears like the first phase of the e2e-provisioning test which provisions a runtime sometimes returns false-positive results. We don't have logs if test succeeds, but we can search for them on stackdriver.

If the test is succeeded we try to execute tests on runtime, but without config map & secret created in the test's first phase, it fails.

**Comment by PK85** [comment]
Closing. Issue doesnt exist anymore.
