### ISSUE TITLE
Define and implement MVP error handling in Director

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#1326]
**AC**
- Define and implement minimal set of error types (e.g. TENANT_NOT_FOUND, ENTITY_NOT_FOUND, etc.)

**Technical requirements:**
- Reuse `gqlerrors` package from Console Backend Service or write something similar, but better
- return machine-readable error codes using https://gqlgen.com/reference/errors/
- Log internal errors in Resolvers using `logrus`
- Remember about wrapping errors
- unification of error handling across all layers
- suggestion: write possible errors in comments for GraphQL operations

**Comment by dbadura** [comment]
Things to do:

- [ ] Replace old `apperros` library with the new one
- [ ] Fix unit tests
- [ ] Fix integration tests
- [ ] Write documentation: How we implemented errors handling, what kind of errors are expected with their code, describe error response structure
- [ ] Look at tenant mapping handler
- [ ] Check other components like `Compass-Runtime-Agent` and `Kyma Environment Broker` @dbadura 
- [ ] Replace `errors.New()` with `apperros` when it fits. @kfurgol  
- [ ] Add `apperros` in input validation
- [ ] Investigate issue https://github.com/kyma-incubator/compass/issues/766
- [ ] Clean up `apperrors` library, extract messages to consts and etc.
- [ ] Merge Constraint Violation with Invalid Data error
- [ ] Implement `repo.helpers` in `Label Definition` repository. @dbadura
