### ISSUE TITLE
KEB is unavailable for a transient period during rolling update

### ISSUE THREAD

**Issue by ebensom** [kyma-incubator/compass#1341]
**Description**
I have noticed short availability check failures for kyma environment broker during rolling update.
The availability check probes the `http://compass-kyma-environment-broker.compass-system:15020/app-health/kyma-environment-broker/livez` URL, so it goes through the istio proxy and it's probe rewrite/hijack functionality. 
During the failure, no HTTP response was received but the connection was terminated quickly, hence I'm suspecting the istio proxy sidecar terminated the connection. 

I suspect since no K8S readiness probe is specified for the KEB container, the pod is considered ready even though istio proxy is not ready to forward traffic to KEB container. A possible solution could be to specify the same /healthz endpoint for readiness probe, so that the pod is only added to the `Endpoints` resource when the HTTP probe through the istio proxy goes through.

**Comment by polskikiel** [comment]
FIxed in this PR: kyma-project/control-plane#31
