### ISSUE TITLE
Az Eventhub namespace creation fails

### ISSUE THREAD

**Issue by sayanh** [kyma-incubator/compass#1359]
**Description**

Az Eventhub namespace creation fails due to :
```
{"instanceID":"8f4d2b5a-8bd0-4acd-b610-6f5eeef8353f","level":"info","msg":"Retry Operation was triggered with message: Failed to persist Azure EventHubs Namespace [8f4d2b5a-8bd0-4acd-b610-6f5eeef8353f] with error: eventhub.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The specified service namespace is invalid. CorrelationId: 46ea14cc-61e5-4c93-9b7b-17a4027169cf"","operation":"6cab751f-0d68-4672-b93b-7126fef908de","provisioning":"manager","step":"Provision Azure Event Hubs","time":"2020-05-15T11:05:26Z"}
```

Details are in spinnaker pipeline.

**Comment by anishj0shi** [comment]
Some Additional problems discovered while fixing this issue with Azure Event-Hubs:
If the instance_id (from KEB) is an upper-case GUID, event-hub host is case sensitive in this case and creates a kafka broker with uppercase host address and our extrapolation of kafka host from the primary connection string fails which is in lower case. and this breaks the kafka channel communication with azure.
 to fix this we have to ensure that the name of an event-hub is always lower case
