### ISSUE TITLE
Refactor Shoot provisioning to use queues mechanism follow-up

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#1371]
**Description**

There are the following topics to address: 
- In #1211 we changed logic of provisioning in such a way that one of stages (ShootProvisioning) is no longer valid. We added some logic on component startup that updates database to allow correct operation resumption. The code will no longer make sense once all existing InProgress operations are updated.
- In #1211 we refactored Shoot controller in such a away that it is responsible for audit logs only. As a result we can create separate test for the controller and remove controller startup from resolver_integration_with_gardener_test.go 

**Reasons**

As a result we will get rid of useless code and simplify resolver_integration_with_gardener_test.go

**Comment by janmedrek** [comment]
Moving to KCP repo: https://github.com/kyma-project/control-plane/issues/85
