### ISSUE TITLE
KEB: monitoring

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-incubator/compass#1379]
**Description**

This issue is a follow up task for the [issue](https://github.com/kyma-incubator/compass/issues/1236)
Enhancements, which should be done:
 - move all metrics, which executes SQL selects to another container because we see DB connections used by these metrics. The DB connections chart shows used conenctions by KEB business logic and also by metric collectors (which is not good).
- the instance collector should provide number of failed/succeeded instance (SQL join with operations should be done)

**Comment by polskikiel** [comment]
To do:
- Implement metrics about recently failing provisioning/deprovisioning steps 
- Implement HAP metrics
