### ISSUE TITLE
Enhance tenants query with information about tenant usage

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#1384]
**Description**

We'd like to know if given tenant has been already used by customer.

**Reasons**

Director has a lot of tenants and MPS Operator likes to see tenants that are in use.

**AC**

- enhance *tenants* query with information isInUse true/false

**Technical Solution hint**
- check if tenant has not empty label defitions. If at least one exist it means tenant is in use.

**Comment by kwiatekus** [comment]
Hey.
Filtering of tenants in use should be reflected in the UI.
It seems like a tiny change [here](https://github.com/kyma-project/console/blob/master/compass/src/config/luigi-config/helpers/navigation-helpers.js#L17) - therefore we wont create a dedicated issue for the changes in the ui.
Lets Fix it top to bottom under this issue and include PR to compass UI here.

**Comment by PK85** [comment]
Hi @kwiatekus, please take into account that your tiny change doesn't include the required change in the search details, where user should see inUse, and if typing then all (inUse on top)

**Comment by pkosiec** [comment]
Hi there, we discussed it offline and the final field name will be `initialized. Cheers!
