### ISSUE TITLE
Metrics for the Runtime Provisioner

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#1385]
**Description**

For maintaining purposes the Runtime Provisioner needs to have a proper monitoring setup.

The starting base for the metrics would be for example:

- average time of succeeded operations
- active provisioning operations
- a number of failures and time required per phase:
  - creating cluster
  - Kyma installation
  - Kyma configuration

Grafana dashboards should be created and visible in the MPS environment.

**Dependencies**
Initial version (operations is progress): 
- Compass: https://github.com/kyma-incubator/compass/pull/1399
- Kyma: https://github.com/kyma-project/kyma/pull/8625#pullrequestreview-421135812

**Comment by ksputo** [comment]
Regarding `active/successful/failed provisioning operations` - in case of having failed operation in the system, we should consider showing the failure reason for the step from operation (e.g. `WaitingForInstallation` step failed on component X or `CleanupResources` step failed to delete ServiceInstance Y)

\cc @PK85
