### ISSUE TITLE
Move the Agent Configuration Job out of Compass chart

### ISSUE THREAD

**Issue by kjaksik** [kyma-incubator/compass#1419]
**Description**

This issue is a follow-up of #1405. We need to move the Agent Configuration job somewhere else.
**Reasons**

We are getting rid of the Compass chart on Kyma repo, and since it's specific for the Compass with Runtime Agent scenario it's not really needed on the Compass repo.

**Comment by pkosiec** [comment]
We need to remove it once Runtime Agent is gone.
