### ISSUE TITLE
Allow to update only basic application attributes

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#142]
**AC**
- Update and merge @tgorgol investigation
- Notify UI team about the changes
- Change update mutations for Application: 
  - Use different input for update and creation
  - Define update input without any references to webhooks, documents, etc.
  - check if runtime create & update mutations work the same way
  - update integration tests
- ~handle a case where user wants to remove all APIs(docs, etc) from application~ out of scope

**Reasons**
To update application name, user should use `updateApplication` mutation and send just Application object, without webhooks, docs, apis and any other references. The same thing is with the Runtimes.

**Comment by pkosiec** [comment]
See the PR for more details: https://github.com/kyma-incubator/compass/pull/173

**Comment by pkosiec** [comment]
As discussed, we will change `update` mutations to update only root objects, for example.:

```graphql
input ApplicationCreateInput {
    name: String!
    description: String
    labels: Labels
    webhooks: [WebhookInput!]
    healthCheckURL: String
    apis: [APIDefinitionInput!]
    eventAPIs: [EventAPIDefinitionInput!]
    documents: [DocumentInput!]
}

input ApplicationUpdateInput {
    name: String!
    description: String
    labels: Labels
    healthCheckURL: String
}
```

**Comment by aszecowka** [comment]
Please ensure that [this](https://github.com/kyma-incubator/compass/pull/280/files) investigation document is merged
