### ISSUE TITLE
Provisioning may timeout to early when waiting for Gardener to assign domain

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#1457]
**Description**

Runtime provisioning may timeout while waiting for Gardener to assign the domain. 
The Provisioning fails with such log:
```
ime="2020-06-23T09:33:06Z" level=info msg="Starting processing" Component=Executor OperationId=1dd32f20-b12f-42dc-bbbf-b11b1bad0f28 OperationType=PROVISION RuntimeId=ad03391d-ab97-4fd8-bbc4-f0ec4490b7a7 Stage=WaitingForClusterDomain
time="2020-06-23T09:33:06Z" level=warning msg="DNS Domain is not set yet for runtime ID: ad03391d-ab97-4fd8-bbc4-f0ec4490b7a7" source="wait_for_cluster_domain.go:61"
```
The cluster was provisioned successfully by Gardener after some time.

Todo:
 - Investigate and adjust the proper timeout for waiting for the cluster domain step.

**Expected result**

Provisioning does not fail on the step if it was executed successfully on the Gardener side.

**Actual result**

Provisioning may fail if waiting for a domain takes longer.

**Comment by janmedrek** [comment]
Moving to the KCP repo: https://github.com/kyma-project/control-plane/issues/91
