### ISSUE TITLE
Fix tests on Compass periodic job

### ISSUE THREAD

**Issue by kfurgol** [kyma-incubator/compass#146]
**Description**

The tests on the `kyma-gke-compass-integration-periodic` job are failing. It should be fixed.  There are also some minor tasks to do with the job:
  - Do not use let's encrypt to generate certificates.
  - Move `installer-cr-cluster-with-compass.yaml.tpl` file from `test-infra` repo to `compass`

**Expected result**
The tests are passing.

**Actual result**
The tests are failing.

**Acceptance Criteria**
- Test are passing
- Cr file is moved to compass repo
- Let's encrypt is not used in this job

**Troubleshooting**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-compass-integration-periodic/1151280471737372673

**Comment by akucharska** [comment]
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-gke-compass-integration-periodic/1151642860446027778
