### ISSUE TITLE
Compass as a Central Management Plane Installation problem.

### ISSUE THREAD

**Issue by DimitarPetrov** [kyma-incubator/compass#1464]
### Description
I tried installing Compass as a Central Management Plane on a Gardener cluster as described [here](https://kyma-project.io/docs/components/compass/#installation-enable-compass-in-kyma-kyma-compass)

Everything was installed correctly, but Dex was not accessible at all and due to this some of the components was not working properly.

After some  investigation I have found that the Istio virtual service of Dex `dex-virtualservice` in `kyma-system` namespace was pointing to non-existing `kyma-system/kyma-gateway` istio gateway. When I edited the `dex-virtualservice` to point to `compass-system/compass-istio-gateway` everything works fine.

**Comment by pkosiec** [comment]
Hi @DimitarPetrov,
Yesterday I merged documentation update for Compass installation in both modes: https://github.com/kyma-incubator/compass/pull/1505. The instruction should be complete now. Let us know if it works. In case of any problems, please reopen the issue. Cheers!
