### ISSUE TITLE
Adjust downloading artifacts for Kyma releases after 1.14

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#1468]
**Description**

Currently, Provisioner fetches artifacts from GitHub releases of Kyma.
After version 1.14, there is a plan to remove the release artifacts of Kyma Installer YAML. 
The Provisioner needs to be adjusted to fetch artifacts directly from the GCS buckets.
Related issue in Kyma: https://github.com/kyma-project/kyma/issues/8360

Things to consider:
- Adjust Provisioner artifacts downloading logic
- Make sure new way of installation is supported by Hydroform
- Adjust acceptance tests logic of creating components list

**Comment by rakesh-garimella** [comment]
The artifacts will still be stored on GCS buckets but instead on one there will be two artifacts `installer.yaml` and `installer-cr.yaml`

**Comment by franpog859** [comment]
Here you can find more info about the bucket organization - https://github.com/kyma-project/test-infra/issues/2562

**Comment by desislavaa** [comment]
Fixed in the Provisioner component, which is now in the `kyma-project/control-plane` repo, with https://github.com/kyma-project/control-plane/pull/41
