### ISSUE TITLE
Provision Kyma with Natss and Disable Kafka Charts using KEB

### ISSUE THREAD

**Issue by anishj0shi** [kyma-incubator/compass#1497]
As a part of provisioning low cost light weight kyma. we need to provision Kyma without the *knative-eventing-kafka* chart and use Natss (with InMemory persistence) as the underlying messaging channel. For this we need to disable the event-hub-step and disable the installation of knative-eventing-kafka chart and enable installation of natss components. mainly *natss-streaming* and *knative-provisioner-natss* 

**AC**
- [ ] Disable kafka charts if the selected plan for provisioning is *kymaruntime:trial*
- [ ] For the above plan, install kyma with natss as messaging layer.
- [ ] natss should not claim a separate persistence volume so the installation needs to be configured accordingly. (w.r.t https://github.com/kyma-project/kyma/issues/8099)

**Comment by piotrmiskiewicz** [comment]
be aware, Kyma Environment Broker is moved to new repo: https://github.com/kyma-project/control-plane
