### ISSUE TITLE
Proposal on how to introduce the Natss provisioner Step with KEB

### ISSUE THREAD

**Issue by anishj0shi** [kyma-incubator/compass#1501]
Come up with a Proposal to introduce Natss Provisioning Step for kyma Runtime provisioning in KEB. 

**AC**
- [ ] A Document which explains the right way to introduce either a new step or refactor the existing event-hub step in KEB to accommodate other messaging systems like NATSS and later EMS, based on Broker Plan.

**Comment by radufa** [comment]
The first approach to extend the existing KEB for supporting Eventing deployment on trial environment was summarized in the PR: https://github.com/kyma-project/control-plane/pull/95
It implies minimal changes to the current KEB implementation to get the trial deployment of Eventing ready asap.
This pragmatical direction to go now, was based on a discussion with Piotr Miskiewicz, which accepted ("looks good") the solution proposed  in the PR.
