### ISSUE TITLE
Enable Agent to fetch configuration for Runtime

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#151]
**AC**

- fetch the Runtime configuration the Runtime Agent by calling applicationsForRuntime(runtimeId: ID!) query offered by Director (as separate PR)

See flow details:
- https://github.com/kyma-incubator/compass/blob/master/docs/architecture/runtime-agent-contract.md

**Comment by pkosiec** [comment]
For now we don't have labeling and pagination, so please return a fixed page with for example all apps.
