### ISSUE TITLE
Upgrade kyma version to 1.16 

### ISSUE THREAD

**Issue by piotrmsc** [kyma-incubator/compass#1553]
**Description**

Once kyma 1.16 will be released compass needs to be adopted to be able to run with kyma 1.16. Currently compass is running on older kyma version. 

**Kyma context**
Kyma 1.16 has changes in the tracing component, namely, health checks were added which now makes helm wait until application will be ready. 
Current prow pipelines create TLS certificate when compass is installed,however, compass installation is not done in parallel with kyma installation. Therefore tracing keycloak proxy fails to reach dex (also kyma component) because ingress gateway does not have TLS secret and rejects connections on port 443.

With upgrade to kyma 1.16 TLS handling should be redesigned, there are couple of ways to do, solution should  be picked by the owners. Moving secret+ gateway to kyma or installing compass in kyma gateway mode or others.
Currently TLS definition is here https://github.com/kyma-incubator/compass/tree/master/chart/compass/charts/gateway/templates

Also in kyma 1.16 there will be new format of istio overrides, so any old overrides will need to be migrated to IstioOperator format. See an example here https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gke-compass-integration.sh#L160

Once upgraded remember to delete conditional handling of resources (for example istio policy and peer authentication) 

**Reasons**

Kyma is evolving and next versions are planned with istio 1.7. Staying on older kyma kyma  with istio 1.4 will block very soon pipelines for kyma and compass. Compass needs to be up to date with released kyma versions otherwise we will end up in deadlock.

**Attachments**

**Comment by dzahariev** [comment]
@piotrmsc , the link https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gke-compass-integration.sh#L224 do not seem to be correct. Can you please check it.
