### ISSUE TITLE
Update the Compass installation document

### ISSUE THREAD

**Issue by majakurcius** [kyma-incubator/compass#1607]
**Description**

The command in the **NOTE** panel in the [Compass installation document](https://github.com/kyma-incubator/compass/blob/master/docs/compass/04-01-installation.md#cluster-installation-1) no longer works:

```bash
kubectl get configmap -n kyma-installer {OVERRIDE_NAME} -oyaml --export | kubectl apply -n compass-installer -f -
```
Apparently, `--export` does not work with the new CLI.

**Expected result**

The command given in the documentation should do the trick.

**Actual result**

The command given returns an error.

**Steps to reproduce**

Follow [this tutorial](https://github.com/kyma-incubator/compass/blob/master/docs/compass/04-01-installation.md#cluster-installation-1).

**Comment by desislavaa** [comment]
Took an year and a half, but the issue is fixed - new mechanism to copy the configmap is present
