### ISSUE TITLE
Support auths for Fetch Request in Director

### ISSUE THREAD

**Issue by franpog859** [kyma-incubator/compass#1629]
**Description**

Currently, auth for Fetch Request is unsupported in Director. We may want to work on it to enable it in the future

Acceptance Criteria:
- A registered OData Spec secured with basic-auth is displayed in the Compass API Package UI and in the Kyma Catalog UI

**Reasons**

Secured Spec could be a valuable feature and it seems that there are such use cases

For more details about the use cases, contact @akrausesap or @janmedrek (please, edit this issue if I got it somehow wrong)

**Attachments**

Here is [an issue](https://github.com/kyma-project/kyma/issues/9863) where we thought that it is a bug

<img width="1396" alt="Screenshot 2020-11-24 at 08 37 33" src="https://user-images.githubusercontent.com/32485355/100062716-5720b000-2e30-11eb-8603-2f904f068ae5.png">

**Comment by desislavaa** [comment]
Fixed with https://github.com/kyma-incubator/compass/pull/1668
