### ISSUE TITLE
Prepare integration tests for labeling

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#166]
**AC**
- Define what we want to test with integration, when it comes to the whole labeling feature (for example, checking if LabelDefinition has been created while adding a label with new key). Cover Label and LabelDefinition use cases.
- Write defined test cases
- Generate examples

**Comment by kfurgol** [comment]
List of cases we want to cover with tests:

```
1. Create label alone (check if label definition was created internally)
2. Creating label against LabelDefinition and using it on a resource (check if it is set correctly)
3. Editing LabelDefinition with incompatible data so it should fail, then try with correct data
4. Deleting LabelDefinition:
 a. deleteRelatedLabels parameter set to true 
 b. deleteRelatedLabels parameter set to false 
5. Try to delete scenario label, should fail
6. Try to remove default value for scenario label, should fail
7. Check if create first application for given tenant creates label definition Scenario and label given app with scenario=default
8. Search by labels (can be done on label Scenario)
 a. check if label exists (value is not important)
 b. check specific label value
```

**Comment by PK85** [comment]
Add tests:
- list LDs
- one scenario required, could be not "default", when deleting last one, fail

**Comment by dbadura** [comment]
* Search by labels (can be done on label Scenario)
 a. check if label exists (value is not important)
 b. check specific label value
version for runtime
