### ISSUE TITLE
API - Multiple credentials for APISpec support

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#17]
**AC**
- [ ] Our Application API must support a way to register application with many APISpec credentials. That means, for example: we have one application and that application is registered to two runtimes. They should be able to use different credentials to call given Application API like *PromotionsAPI*
- [ ] Also. make a modification in `APIDefinition` versioning - to know when an `APIDefiniton` is a new version for another `APIDefinition`.

**Comment by akrausesap** [comment]
On top of credentials we also need support for specific headers and query parameters. These query parameters can be applied in 3 different situations:

* Fetching Metadata
* Requesting an OAuth2 token with client credentials
* Making a call to the API at runtime

All options might require a different combination of headers and query parameters.

**Comment by ormos** [comment]
From my perspective we should avoid using the term credentials here. Every API-Endpoint which got registered through an APISpec should specify and AuthenticationMethod, while AuthenticationMethod is something abstract. 

So credential with principal and password is one AuthenticationMethod, and Headers or Query Parameters might be just optional additional parameters. 

Another AuthenticationMethod might be something like OAuth2 or SAML. And with that concept we can extend the model in the future. Event some STS might be an option so exchange an internal token to sime token which might be used for authenticating against the external application API.

I would strictly avoid that we manage a list of credentials. In that case the AuthenticationMethod needs to provide the right authentication data (Credentials, tokens, api-keys, etc) depending on the context the call is made.

**Comment by aszecowka** [comment]
@akrausesap, @ormos in  kyma-incubator/compass#19  I tried to address your comments, in addition to `Credential` we introduced new type `Auth`:
```
type Auth {
    credential: CredentialData!
    additionalHeaders: HttpHeaders
    additionalQueryParams: QueryParams
    requestAuth: CredentialRequestAuth
}
```

This type can be used to define how `APISpec` is fetched,  how to make an API call. 
Feel free to add comments to my PR.
