### ISSUE TITLE
Provide stage compass cluster

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#183]
**AC**
- provide pipeline for stage compass
- secure configuration and credentials
  - extension service configuration
  - LMS configuration (fluentD)
- prepare Kyma installation yamls for compass only, and runtime only. 
- support upgrade in CI, for new versions of Kyma
- prepare a GCP Postgress instance

**Comment by mwieczorek** [comment]
Pipeline in concourse created
All secrets required by pipeline stored in Vault
Yaml installation files for 'compass-only' prepared, stored in GCS as artifacts and used bby the pipeline
Pipeline support upgrade is there (bump version of kyma in pipeline repository and it will be triggered automatically)

GCP cloud SQL - work in progress (TF module and adding it to the pipeline)
