### ISSUE TITLE
Director should support providing documentation for APIDefinition and  EventAPIDefinition

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#198]
**Description**
The user should be able to provide documentation for  APIDefinition and  EventAPIDefinition. 

**Reasons**
When users register their API (REST or Events) they can provide spec (Open API or Async API). However, they cannot specify documentation (e.g. markdown files) complementing specifications.

**Comment by PK85** [comment]
Already implemented. User can send DocumentInput via addDocumentToPackage mutation.
