### ISSUE TITLE
Director should validate CredentialData

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#199]
**Description**
Director should check whether valid credentials data is provided.

**Expected result**
The following cases are considered as invalid:
- API with Basic Auth is registered but data is incomplete (both user and password is empty, etc.)
- API with OAuth is registered but data is incomplete (ClientID, ClientSecret and URL is empty, etc.)
- both Basic Auth and OAuth are specified (there is only on method allowed)

**Actual result**

Director should not allow to register API with incomplete credentials data.

**Steps to reproduce**

1. Register an application with API containing incomplete credentials (Basic Auth and Oauth). Notice it is created.

2. Register an application with API containing both types of credentials. Notice it is created.

**Comment by tgorgol** [comment]
Will be fixed in https://github.com/kyma-incubator/compass/issues/255

**Comment by tgorgol** [comment]
Fixed
