### ISSUE TITLE
Extend EventAPIDefinition with additional information about custom event system

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#22]
**Description**

We need to support two ways of using Eventing. Application can:
- not use event messaging system, and then Runtime EventService will be used
- use specific event messaging system, and then Runtime kNativeEventing must be configured properly 

**Reasons**

We need that to support system with already configured eventing system

**AC**
- [ ] extends EventAPIDefinition with additional fields, like URL, Type, Auth, Channel, etc
```
type EventAPIDefinition {
    id: ID!
    spec: EventSpec!
    version: Version
}
``` 
- [ ] Add architecture diagram about those two possibilities how to Eventing works with Kyma Runtime

**Comment by abbi-gaurav** [comment]
Hi @PK85, 
Will this be complementing the task https://github.com/kyma-project/kyma/issues/3018?
In this, we need to support the possibility of a customer using an eventing backend of his choice while still getting the same developer experience as it is with current kyma eventing.
