### ISSUE TITLE
Extend contributing.md with development best practices 

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#222]
**Description**
We should have a single place where we define development best practices to keep our source code consistent. Example of information that can be included:
- error handling
- how to manage transactions
- how to write repository layers
- responsibility of all layers: resolvers, service, repository

**Reasons**
- consitent code
- all discussions about code structure are persisted in the repo

**Comment by PK85** [comment]
closing for now, as we will not work on director.
