### ISSUE TITLE
Authentication and authorization for compass services

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/compass#261]
**Description**
Access to compass services should be secures. It should be possible to authenticate users and systems (applications, application helpers, runtime agents) accessing compass API. Each user and system can have different authorizations that are stored in scopes.

**Reasons**
Compass should support multiple authentication methods (OAuth 2.0 + OpenID Connect, client certificates). Compass services should not deal with authentication methods details. Gateway and supporting components (OathKeeper from Ory) should cover authentication and provide authorizations (scopes) in the unified form easy to consume by upstream services.

**Comment by janmedrek** [comment]
As we understand it right now this needs to be done regarding certificates:
- New mutator for validating one-time tokens
- New mutator for validating istio certificate headers
- Istio mTLS configuration
- Adjustments in Connector Service

**Comment by pkosiec** [comment]
@janmedrek 
> Translating Client ID (App, Runtime) to Tenant ID (required for Director calls with certificates)

It is related to OAuth 2.0 case only, so we will take handle this.
