### ISSUE TITLE
Define coding best practices for Director

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#266]
**Description**
Example of topics that should be covered: 
- how to implement repository
  - use helpers from repo package
  - entity defined in `entity.go`, use sql.NullString types etc.
  - converter is responsible for converting from/to Entity

- define the responsibility of Resolver
  - loading tenant from context
  - begin/commit/rollback transaction
  - conversion from/to Graphql objects

- how to handle errors:
  - client errors vs internal errors
  - wrapping errors
  - repository errors: NotFound error, when they should be returned.
Should we check if resource exists before we try to delete it? Should we check "rowsAffected" after deleting, and if for some reason it's equal to 0 return error?

- describe how do we ensure tenant separation

**Reasons**
To have a consistent codebase.

**Comment by crabtree** [comment]
We may need to split the entites<>model conversion from gql<>model conversion. If we put this into one converter I think we break the single responsibility of that component. Just take a look into the existing one, for example, converter.go from the application domain. This particular converter makes use of other converters when doing its job on gql<>model conversion but on the other hand, when working with entity it acts as a simple mapper.

**Comment by pbochynski** [comment]
Closed due to inactivity.
