### ISSUE TITLE
Implement tenant mapping service for Compass

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#288]
**Description**
Implement Tenant (Mapping) Service according to proposal #278 

**AC**
- client_id to tenant mapping for cert and client_credential flow (we will query DB for client_id in Runtme auth or application Auth and get tenant for corresponding app or runtime)
- in production env tenant will be passed with request, on local development we need a mapping between user and tenant and scopes (configMap)
  - assign 3 tenants from chart for UI to given users
- ~use dedicated user for calls to DB~
- tests only for TenantMapping Service
- Fix scopes in cert flow in code (use configmap)

See and verify things to do from proposal: https://github.com/kyma-incubator/compass/blob/master/docs/architecture/authentication-and-authorization.md

**Comment by PK85** [comment]
Cert flow (from where to get attributes), check with corresponding team that works on that

**Comment by aszecowka** [comment]
- can compass UI switch tenants? @PK85 
- proposed configmap structure (depends on prev question):
```
johnDoe@gmail.com: {
  tenants:[{dispayName, id}]
 scopes: ["scope_a", "scope_b"]
}
```

**Comment by PK85** [comment]
> can compass UI switch tenants? @PK85 
Answer: 
- yes for static local user by dex. Such a user could be assigned too many tenants. And tenant selection is required.
- not really for users that come from outside and are authenticated by extel idernal identity providers, cause they are already logged into given tenant. But of course I assume they can switch tenant as well.
