### ISSUE TITLE
Secure Director GraphQL queries and mutations

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#289]
**Description**

- Implement HTTP middleware for Director. It will get JWT token, [validate](https://www.ory.sh/docs/oathkeeper/pipeline/mutator#id_token) and unpack it to get client scopes and tenant. It will put them into request context @kfurgol 
- Implement GraphQL directive which loads a file, where are required scopes for queries/mutations are defined (use ConfigMap and mount it to Director) - remember about reloading the file e.g. once per minute @aszecowka 
- Set directives for all queries and mutations, and also resolvers for related objects. The access rules have to be set dynamically (you cannot fix them inside GraphQL schema) @aszecowka 
- Add all scopes for requests in certificates flow in tenant mapping handler (temporary solution before actual Tenant Mapping Handler) @aszecowka 
- Test Director logic with scopes using fixed JWT tokens (without OathKeeper involvement) - rework current tests @pkosiec 
- Test scopes authorization functionality in integration tests @pkosiec 
- Define scopes:
   - for mutations: application:admin, runtime:admin, integration_system:admin
   - for queries: application:view, runtime:view, integration_system:view

**Comment by PK85** [comment]
consider support tenant header and JWT token. Tests still go with header. When Tests adjusted we can make JWT as the only option. Check if UI still works.
