### ISSUE TITLE
Secure auth-related resolvers for Runtime with authorization directives

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#306]
**Description**

Secure auth-related resolvers for Runtime with authorization directives:
```graphql
auth(runtimeID: ID!): RuntimeAuth!
auths: [RuntimeAuth!]!
```

**AC**
- Proposal - discuss with team
- Agent shouldn't be able to call `auth` resolver with different ID than its own.
- Agent should be able to see only one item in `auths` list
- Application should be able to see all runtime auths connected to the application (via `auth` and `auths` resolvers).
 
**Reasons**

We need to limit Runtime auths list seen by Agent to just single element.

**Comment by pkosiec** [comment]
We could extend Tenant Mapping Service with passing appID/rtmID to request context. Then we can reuse it for another directive

**Comment by pkosiec** [comment]
Please see my short investigation, how we can do it:
https://github.com/pkosiec/compass/commit/d85bca522f3db8701111ca1b9e4be02c6b471314

**Comment by dbadura** [comment]
In the proposal we will show how to use `hasScope` directive for `auths` fields and will introduce new directive: 
```graphql
limitFor(consumerType, idField)
```

**Comment by pkosiec** [comment]
We will reevaluate this topic: https://github.com/kyma-incubator/compass/issues/1301
