### ISSUE TITLE
Prepare Compass E2E tests

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#307]
**Description**
- Test OathKeeper integration - create brand new separate test (with one GraphQL operation per subtest)
   - with JWT token issued by Dex with static user
   - with OAuth2.0 access token
   - ~with certs~ - Framefrogs will test it in runtime agent 
- Rename current tests to `director-tests`. One Docker image. Two TestDefinitions.

**Test Scenario**
- Get Dex token, create IntegrationSystem with it and generate client credentials for IntSystem
- ~Get Integration system as user, read auth field with client_id and client_secret for it~
- Call Hydra for OAuth 2.0 access token with client_id and client_secret pair - https://github.com/kyma-incubator/examples/tree/master/ory-hydra/scenarios/client-credentials
- Create an Application (as Integration System)
- Add example API Spec using issued OAuth2.0 Access token (as Integration System)
- Remove application as user (using JWT token from Dex)
- Explicitly remove System Auth with client credential (this is an additional step, until we fix #375)
- Remove IntegrationSystem as user (using JWT token from Dex)
- Test if token granted for IntegrationSystem is invalid
- Test if IntegrationSystem cannot fetch token

**Reasons**
We need to test if the whole OathKeeper integration works.

**Comment by kfurgol** [comment]
Code for fetching dex token can be found here https://github.com/kyma-project/kyma/tree/master/tests/integration/dex/dex

**Comment by aszecowka** [comment]
> Get Integration system as user, read auth field with client_id and client_secret for it

- it looks that we are missing creating integration system
- when auth field for IntegrationSystem is populated. What about security, let assume that 2 IntegrationSystems can work for the same tenant, can one integration system read auths for the second one?

**Comment by aszecowka** [comment]
Updated Test Scenario:
- Get Dex token, and create IntegrationSystem with it
- Get Integration system as user, read auth field with client_id and client_secret for it
- Call Hydra for OAuth 2.0 access token with client_id and client_secret pair - https://github.com/kyma-incubator/examples/tree/master/ory-hydra/scenarios/client-credentials
- Create an Application (as Integration System)
- Add example API Spec using issued OAuth2.0 Access token
- Remove application as user (using JWT token from Dex)
- Remove IntegrationSystem as user (using JWT token from Dex)
- Test if token granted for IntegrationSystem is invalid
- Test if IntegrationSystem cannot fetch token
