### ISSUE TITLE
Manage Integration Systems in Compass

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#311]
**Description**
We need to provide credentials for integration system by which they can call Compass API

**AC**
- Create DB table for Integration System (ID, name, ~scopes~) @tgorgol 
- For now Integration System can operate within any tenant @tgorgol
- Integration System is global entity (no tenancy) @tgorgol
- integration system has multiple auths (SystemAuth), similarly like in Runtime @tgorgol
- Add create, get, list (paginated), update and delete mutations for Integration System @tgorgol 
- add mutations: addClientCredentials (set scopes to allow integration system managing applications), deleteClientCredentials by ID: @pkosiec 
   - generate client_secret, get SystemAuth ID as client_id and call hydra with scopes
   - fetch scopes from static configmap during client_id/client_secret pair during generation
   - [x] fix scopes in configmap for only managing applications 
   - [x] double check if client can introspect available scopes from public hydra endpoint - if not, create follow up task for that: DONE https://github.com/kyma-incubator/compass/issues/362
  - [x] on SystemAuth delete call hydra and remove registered client
- prepare integration tests @kfurgol 

out of scope: UI

**Reasons**
Allow integration system to register any Application within multiple tenants

**Comment by PK85** [comment]
1) Next iteration we will add a list of tenants that IS could work with.
2) list of tenants is updated when application is created from AppClass from given IS

**Comment by aszecowka** [comment]
how IntegrationSystem provide the tenant in which context it is working (by headers?)? What integrationSystem provide, external tenant or internal tenant? Where tenants mapping is performed?

**Comment by aszecowka** [comment]
> generate client_secret
make an HTTP call to hydra, please double check if this endpoint will not be removed in the future.

**Comment by PK85** [comment]
> how IntegrationSystem provide the tenant in which context it is working (by headers?)? What integrationSystem provide, external tenant or internal tenant? Where tenants mapping is performed?
> 
> Our assumtption: we work on internal tenant

I guess header is a way to go. And right now as we don't have external tenant to  our tenant mapping it shoudl IS should send internal one. That's a temporary solution. We will use only exteral tenant in the future.

**Comment by pkosiec** [comment]
In future we need to clean up Hydra clients for all deleted Applications, Runtimes and Integration System:
https://github.com/kyma-incubator/compass/issues/375
