### ISSUE TITLE
Proposal for ApplicationTemplates

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#339]
**Description**
ApplicationClass by design belongs to given integration system. User select ApplicationType and gets a token. Every IntegrationSystem could bring new OneTimeToken Service. Could work as a Appplication Template in the future, to contain APIs spec, and so on.

**AC**
- document how ApplicationClass API looks like
- how relation between ApplicationClass  and integrationSystem looks like (wordpress as an ApplicationClass)
- full flow from IntegrationSystem creation, then AppClasses registration and App creation is described
- decide how we can use additional OneTimeTokenService for given IntegrationSystem

**Glossary**
Think about names, ApplicationClass, ApplicationType etc

**Comment by aszecowka** [comment]
@PK85 
Questions:
-  ApplicationClass == ApplicationType ?
- to consider: can we treat connector as an IntegrationSystem?
- currently in GraphQL API we have: 
`generateOneTimeTokenForApplication(id: ID!): OneTimeToken` and `OneTimeToken` is defined in the following way: 
`
type OneTimeToken {
	token: String!
	connectorURL: String!
}`

are token and URL enough information to support all possible flows?
- what defines which OneTimeTokenService should be used, ApplicationType or IntegrationSystem?

- when I choose ApplicationClass X, when I decide how trusted relation between Runtime and Application is established?

- let assume that we have following communication paths: App <--> RTM, App <--> MP, RTM <--> MP. Is `TokenProvider` responsible for all communication paths, or I can have different `TokenProviders` for every path. 

- Integration System:
  - can work for many tenants
  - register ApplicationClass
