### ISSUE TITLE
Add GraphQL query for getting OAuth2.0 client scopes from Hydra

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#362]
**Description**

Add GraphQL query for OAuth2.0 access token introspection.
Call Hydra internal endpoint https://www.ory.sh/docs/hydra/sdk/api#get-an-oauth-20-client

See #311 

**Reasons**

Client (Application/Runtime/Integration System) should be able to check scopes for itself, assigned while generating client_id/client_secret pair.

**Comment by PK85** [comment]
wont fix
