### ISSUE TITLE
Good, old Dependency Injection in Compass Director

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#386]
Currently, most of our services, converters, and repositories are instantiated in `root_resolver.go`.
But for some cases, we instantiate those services in `cmd/main.go`, see `getTenantMappingHanderFunc`.
UIDService, as an example, is instantiated in both places, so we have 2 instances of the same object.

All services should be instantiated in one place (`main.go`). Access to them should be possible from `Container` object, that is passed on to the RootResolver etc.

**Comment by crabtree** [comment]
I would go even further and suggest a refactoring of `cmd/main.go` to make it more structured. I'd remove all the implementation details from this file and move them to desired packages or at least functions that encapsulate those details.
