### ISSUE TITLE
Provisioner must validate runtime identifier 

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#393]
**Description**

Provisioner API allows to perform various operations (e.g. provisioning, upgrade, deprovisioning) in a form of GraphQL mutations. Runtime identifier is a mandatory parameter for each mutation supported by the API. 
When provisioning is started provisioner should verify whether the identifier is correct by performing call to Director API. Other operations (deprovisioning, upgrade, etc.) should rely on database (if runtime id cannot be found in database it is considered as invalid)

**Reasons**

In order to maintain consistency across the system as a whole runtime identifier passed to Provisioner needs to exist in Director's database before provisioning can be started.

**Comment by janmedrek** [comment]
This issue is no longer valid - Provisioner will be the one registering runtime in Director, there is no need to verify it (since it comes from the source of IDs itself).
