### ISSUE TITLE
Document Compass Provisioner component

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#396]
**Description**

We need to provide proper documentation for the Provisioner component.

**Reasons**

Right now Provisioner has no user-friendly documentation, we need to provide a description of how it works and what needs to be done in order to perform a specific set of actions with the use of Provisioner.

**Acceptance Criteria**
- Basic concepts of Provisioner described and linked in [this document](https://github.com/kyma-incubator/compass/blob/master/docs/architecture/mp-components.md)
  - [ ] Pre-requisites of Provisioner (cluster infrastructure, secrets, ...)
  - [ ] Description of how clusters are provisioned (Hydroform use, hyperscaler communication, privileges needed for service accounts / service principals)
  - [ ] Chart values described
  - [ ] Parameters described
- Example scenarios covered (including GraphQL calls):
  - [ ] Saving credentials in cluster that Provisioner will use (secret creation)
  - [ ] Provisioning cluster with Compass Provisioner
  - [ ] Deprovisioning cluster with Compass Provisioner
  - [ ] Cleaning up runtime data

**Comment by majakurcius** [comment]
@janmedrek The file you link to does not exist. Do we need it or is the first entry on the AC list exhaustive?

**Comment by janmedrek** [comment]
@majakurcius please use this link: https://github.com/kyma-incubator/compass/blob/master/docs/architecture/components.md
