### ISSUE TITLE
Runtime Provisioner - perform config validation before starting provisioning

### ISSUE THREAD

**Issue by Maladie** [kyma-incubator/compass#400]
**Description**

Currently, cluster configuration parameters are validated after sending them to Hydroform when provisioning is already started. Runtime Provisioner should perform its own validation whenever it is possible.

Additionally, there is a need for an API change for the GCP configuration as it should accept regional or zonal configuration. It needs strict validation, so it should be done together with this improvement.

**Reasons**

It will greatly improve user experience because now we need to make a call to check operation status to see if the configuration is correct.

**Acceptance Criteria:**
- [ ] Provide concept on using dynamic configuration mechanism (DB, configmap, ...)
- [ ] Cluster configuration parameters validated
- [ ] GCP config validates zonal and regional configurations
- [ ] Configuration documented with examples

**Comment by piotrmiskiewicz** [comment]
In case of wrong provisioning input parameters KEB should get something like error code/name so KEB could know if it is a temporary error (like networking error) and must retry or some value is incorrect and should fail. See: https://github.com/kyma-incubator/compass/issues/1099

**Comment by janmedrek** [comment]
Moving to the KCP repo: https://github.com/kyma-project/control-plane/issues/90
