### ISSUE TITLE
Director GraphQL API Hardening

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#401]
After another review of our GraphQL API, we noticed that we have some inconsistencies. 

Proposed improvements:
- API should always be capitalized
- rename API and EventAPI to APIDefinitions and EventDefinitions
- rename IntegrationSystem to ApplicationsDelegateInput. IntegrationSystem for Applications and Runtimes should be separated.
- rename mutations `create...` to `add...`  - because we do not create Application or Runtime, we just register it in Compass. `register` and `unregister` can be awkward so I propose to use `add`.
- `generate...` mutations replaced with `request...` - as an end-user, I don't have to know that for example Token is generated or not. 
- `deleteSystemAuth...`  renamed to `invalidateSystemAuth...`
- **new incosistency**  for type field in EventAPISpecInput and APISpecInput
```
input EventAPISpecInput {
	eventSpecType: EventAPISpecType!

}

input APISpecInput {
	type: APISpecType!
}

```

Below you can find my proposal on how API should be changed. 

```diff
diff --git a/components/director/pkg/graphql/schema.graphql b/components/director/pkg/graphql/schema.graphql
index ce87b164..ec4209c5 100755
--- a/components/director/pkg/graphql/schema.graphql
+++ b/components/director/pkg/graphql/schema.graphql
@@ -42,3 +42,4 @@ enum DocumentFormat {
 
-enum EventAPISpecType {
+
+enum EventSpecType {
 	ASYNC_API
@@ -115,4 +116,4 @@ input ApplicationCreateInput {
 	healthCheckURL: String
-	apis: [APIDefinitionInput!]
-	eventAPIs: [EventAPIDefinitionInput!]
+	APIDefinitions: [APIDefinitionInput!]
+	eventDefinitions: [EventDefinitionInput!]
 	documents: [DocumentInput!]
@@ -164,6 +165,6 @@ input DocumentInput {
 
-input EventAPIDefinitionInput {
+input EventDefinitionInput {
 	name: String!
 	description: String
-	spec: EventAPISpecInput!
+	spec: EventSpecInput!
 	group: String
@@ -172,5 +173,5 @@ input EventAPIDefinitionInput {
 
-input EventAPISpecInput {
+input EventSpecInput {
 	data: CLOB
-	eventSpecType: EventAPISpecType!
+	eventSpecType: EventSpecType!
 	format: SpecFormat!
@@ -186,3 +187,3 @@ input FetchRequestInput {
 
-input IntegrationSystemInput {
+input ApplicationsDelegateInput {
 	name: String!
@@ -292,3 +293,3 @@ type Application {
 	"""
-	apis(group: String, first: Int = 100, after: PageCursor): APIDefinitionPage!
+    APIDefinitions(group: String, first: Int = 100, after: PageCursor): APIDefinitionPage!
 	"""
@@ -296,3 +297,3 @@ type Application {
 	"""
-	eventAPIs(group: String, first: Int = 100, after: PageCursor): EventAPIDefinitionPage!
+    eventDefinitions(group: String, first: Int = 100, after: PageCursor): EventDefinitionPage!
 	documents(first: Int = 100, after: PageCursor): DocumentPage!
@@ -356,3 +357,3 @@ type DocumentPage implements Pageable {
 
-type EventAPIDefinition {
+type EventDefinition {
 	id: ID!
@@ -365,3 +366,3 @@ type EventAPIDefinition {
 	group: String
-	spec: EventAPISpec!
+	spec: EventSpec!
 	version: Version
@@ -369,4 +370,4 @@ type EventAPIDefinition {
 
-type EventAPIDefinitionPage implements Pageable {
-	data: [EventAPIDefinition!]!
+type EventDefinitionPage implements Pageable {
+	data: [EventDefinition!]!
 	pageInfo: PageInfo!
@@ -375,5 +376,5 @@ type EventAPIDefinitionPage implements Pageable {
 
-type EventAPISpec {
+type EventSpec {
 	data: CLOB
-	type: EventAPISpecType!
+	type: EventSpecType!
 	format: SpecFormat!
@@ -412,3 +413,3 @@ type HealthCheckPage implements Pageable {
 
-type IntegrationSystem {
+type ApplicationsDelegate {
 	id: ID!
@@ -419,4 +420,4 @@ type IntegrationSystem {
 
-type IntegrationSystemPage implements Pageable {
-	data: [IntegrationSystem!]!
+type ApplicationsDelegatePage implements Pageable {
+	data: [ApplicationsDelegate!]!
 	pageInfo: PageInfo!
@@ -525,4 +526,4 @@ type Query {
 	healthChecks(types: [HealthCheckType!], origin: ID, first: Int = 100, after: PageCursor): HealthCheckPage! @hasScopes(path: "graphql.query.healthChecks")
-	api(id: ID!): APIDefinition @hasScopes(path: "graphql.query.api")
-	eventAPI(id: ID!): EventAPIDefinition @hasScopes(path: "graphql.query.eventAPI")
+	APIDefinition(id: ID!): APIDefinition @hasScopes(path: "graphql.query.api")
+	eventDefinition(id: ID!): EventDefinition @hasScopes(path: "graphql.query.eventAPI")
 	"""
@@ -530,4 +531,4 @@ type Query {
 	"""
-	integrationSystems(first: Int = 100, after: PageCursor): IntegrationSystemPage! @hasScopes(path: "graphql.query.integrationSystems")
-	integrationSystem(id: ID!): IntegrationSystem @hasScopes(path: "graphql.query.integrationSystem")
+    applicationsDelegates(first: Int = 100, after: PageCursor): ApplicationsDelegatePage! @hasScopes(path: "graphql.query.integrationSystems")
+	applicationsDelegate(id: ID!): ApplicationsDelegate @hasScopes(path: "graphql.query.integrationSystem")
 }
@@ -535,11 +536,11 @@ type Query {
 type Mutation {
-	createApplication(in: ApplicationCreateInput!): Application! @hasScopes(path: "graphql.mutation.createApplication")
+	addApplication(in: ApplicationCreateInput!): Application! @hasScopes(path: "graphql.mutation.createApplication")
 	updateApplication(id: ID!, in: ApplicationUpdateInput!): Application! @hasScopes(path: "graphql.mutation.updateApplication")
 	deleteApplication(id: ID!): Application! @hasScopes(path: "graphql.mutation.deleteApplication")
-	createRuntime(in: RuntimeInput!): Runtime! @hasScopes(path: "graphql.mutation.createRuntime")
+	addRuntime(in: RuntimeInput!): Runtime! @hasScopes(path: "graphql.mutation.createRuntime")
 	updateRuntime(id: ID!, in: RuntimeInput!): Runtime! @hasScopes(path: "graphql.mutation.updateRuntime")
 	deleteRuntime(id: ID!): Runtime! @hasScopes(path: "graphql.mutation.deleteRuntime")
-	createIntegrationSystem(in: IntegrationSystemInput!): IntegrationSystem! @hasScopes(path: "graphql.mutation.createIntegrationSystem")
-	updateIntegrationSystem(id: ID!, in: IntegrationSystemInput!): IntegrationSystem! @hasScopes(path: "graphql.mutation.updateIntegrationSystem")
-	deleteIntegrationSystem(id: ID!): IntegrationSystem! @hasScopes(path: "graphql.mutation.deleteIntegrationSystem")
+	addApplicationsDelegate(in: ApplicationsDelegateInput!): ApplicationsDelegate! @hasScopes(path: "graphql.mutation.createIntegrationSystem")
+	updateApplicationsDelegate(id: ID!, in: ApplicationsDelegateInput!): ApplicationsDelegate! @hasScopes(path: "graphql.mutation.updateIntegrationSystem")
+	deleteApplicationsDelegate(id: ID!): ApplicationsDelegate! @hasScopes(path: "graphql.mutation.deleteIntegrationSystem")
 	addWebhook(applicationID: ID!, in: WebhookInput!): Webhook! @hasScopes(path: "graphql.mutation.addWebhook")
@@ -547,14 +548,14 @@ type Mutation {
 	deleteWebhook(webhookID: ID!): Webhook! @hasScopes(path: "graphql.mutation.deleteWebhook")
-	addAPI(applicationID: ID!, in: APIDefinitionInput!): APIDefinition! @hasScopes(path: "graphql.mutation.addAPI")
-	updateAPI(id: ID!, in: APIDefinitionInput!): APIDefinition! @hasScopes(path: "graphql.mutation.updateAPI")
-	deleteAPI(id: ID!): APIDefinition! @hasScopes(path: "graphql.mutation.deleteAPI")
+	addAPIDefinition(applicationID: ID!, in: APIDefinitionInput!): APIDefinition! @hasScopes(path: "graphql.mutation.addAPI")
+	updateAPIDefinition(id: ID!, in: APIDefinitionInput!): APIDefinition! @hasScopes(path: "graphql.mutation.updateAPI")
+	deleteAPIDefinition(id: ID!): APIDefinition! @hasScopes(path: "graphql.mutation.deleteAPI")
 	refetchAPISpec(apiID: ID!): APISpec! @hasScopes(path: "graphql.mutation.refetchAPISpec")
-	generateOneTimeTokenForRuntime(id: ID!): OneTimeToken! @hasScopes(path: "graphql.mutation.generateOneTimeTokenForRuntime")
-	generateOneTimeTokenForApplication(id: ID!): OneTimeToken! @hasScopes(path: "graphql.mutation.generateOneTimeTokenForApplication")
-	generateClientCredentialsForRuntime(id: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.generateClientCredentialsForRuntime")
-	generateClientCredentialsForApplication(id: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.generateClientCredentialsForApplication")
-	generateClientCredentialsForIntegrationSystem(id: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.generateClientCredentialsForIntegrationSystem")
-	deleteSystemAuthForRuntime(authID: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.deleteSystemAuthForRuntime")
-	deleteSystemAuthForApplication(authID: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.deleteSystemAuthForApplication")
-	deleteSystemAuthForIntegrationSystem(authID: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.deleteSystemAuthForIntegrationSystem")
+	requestOneTimeTokenForRuntime(id: ID!): OneTimeToken! @hasScopes(path: "graphql.mutation.generateOneTimeTokenForRuntime")
+	requestOneTimeTokenForApplication(id: ID!): OneTimeToken! @hasScopes(path: "graphql.mutation.generateOneTimeTokenForApplication")
+	requestClientCredentialsForRuntime(id: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.generateClientCredentialsForRuntime")
+	requestClientCredentialsForApplication(id: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.generateClientCredentialsForApplication")
+	requestClientCredentialsForApplicationsDelegate(id: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.generateClientCredentialsForIntegrationSystem")
+	invalidateSystemAuthForRuntime(authID: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.deleteSystemAuthForRuntime")
+	invalidateSystemAuthForApplication(authID: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.deleteSystemAuthForApplication")
+	invalidateSystemAuthForApplicationsDelegate(authID: ID!): SystemAuth! @hasScopes(path: "graphql.mutation.deleteSystemAuthForIntegrationSystem")
 	"""
@@ -564,9 +565,9 @@ type Mutation {
 	deleteAPIAuth(apiID: ID!, runtimeID: ID!): APIRuntimeAuth! @hasScopes(path: "graphql.mutation.deleteAPIAuth")
-	addEventAPI(applicationID: ID!, in: EventAPIDefinitionInput!): EventAPIDefinition! @hasScopes(path: "graphql.mutation.addEventAPI")
-	updateEventAPI(id: ID!, in: EventAPIDefinitionInput!): EventAPIDefinition! @hasScopes(path: "graphql.mutation.updateEventAPI")
-	deleteEventAPI(id: ID!): EventAPIDefinition! @hasScopes(path: "graphql.mutation.deleteEventAPI")
-	refetchEventAPISpec(eventID: ID!): EventAPISpec! @hasScopes(path: "graphql.mutation.refetchEventAPISpec")
+	addEventDefitnion(applicationID: ID!, in: EventDefinitionInput!): EventDefinition! @hasScopes(path: "graphql.mutation.addEventAPI")
+	updateEventDefinition(id: ID!, in: EventDefinitionInput!): EventDefinition! @hasScopes(path: "graphql.mutation.updateEventAPI")
+	deleteEventDefinition(id: ID!): EventDefinition! @hasScopes(path: "graphql.mutation.deleteEventAPI")
+	refetchEventSpec(eventID: ID!): EventSpec! @hasScopes(path: "graphql.mutation.refetchEventAPISpec")
 	addDocument(applicationID: ID!, in: DocumentInput!): Document! @hasScopes(path: "graphql.mutation.addDocument")
 	deleteDocument(id: ID!): Document! @hasScopes(path: "graphql.mutation.deleteDocument")
-	createLabelDefinition(in: LabelDefinitionInput!): LabelDefinition! @hasScopes(path: "graphql.mutation.createLabelDefinition")
+	addLabelDefinition(in: LabelDefinitionInput!): LabelDefinition! @hasScopes(path: "graphql.mutation.createLabelDefinition")
 	updateLabelDefinition(in: LabelDefinitionInput!): LabelDefinition! @hasScopes(path: "graphql.mutation.updateLabelDefinition")
```

Because these changes will break compatibility we should for some time support old and new API to allow our clients adjust to the new API. 
Remember about updating documentation.

**Comment by pkosiec** [comment]
> API should always be capitalized -  `APIDefinitions: [APIDefinitionInput!]`

That's against SDL convention - field names should start with lowercase letters.

> rename IntegrationSystem to ApplicationsDelegateInput. IntegrationSystem for Applications and Runtimes should be separated.

What about `Delegate` entity with type: Application/Runtime? For now these entities are actually equal, but differ with scopes. Maybe it would be good to clarify what is the future for them, to make a final decision, if we really need to separate them.

> rename mutations create... to add... - because we do not create Application or Runtime, we just register it in Compass. register and unregister can be awkward so I propose to use add.

I vote for `register` and `unregister`, sounds fine

**Comment by PK85** [comment]
I like your idea about `type` attribute under `Delegate` entity.

**Comment by pkosiec** [comment]
@PK85  I like the name "Operator" 👌 
![tenor-108424758](https://user-images.githubusercontent.com/7155799/67293322-8b66c600-f4e4-11e9-8878-891b91390836.gif)

**Comment by aszecowka** [comment]
Let's discuss how to improve our GraphQL API:
Please put your github name (@pkosiec @aszecowka @crabtree @KarolJaksik @dbdura @tgorgol @kfurgol @PK85) next to the option you like the most.
Feel free to add pros and cons for every option.


# API should be always capitalized 

```diff
type Application {
 
-	apis(group: String, first: Int = 100, after: PageCursor): APIDefinitionPage!
+    APIDefinitions(group: String, first: Int = 100, after: PageCursor): APIDefinitionPage!
```


Pros:
- conistency

Cons:
- that's against SDL convention - field names should start with lowercase letters.

Decision:
Yes: 
No: 
abstain: 

# Rename API and EventAPI to APIDefinitions and EventDefinitions

```
input ApplicationCreateInput {
	apis: [APIDefinitionInput!]
	eventAPIs: [EventAPIDefinitionInput!]
}
```

Pros:
- some people claims that there is no such thing as a EventAPI, it is Event or API. 
- our types are APIDefinitionInput, so fields maybe also should be called APIDefinitions, not apis for consistency
Cons:
-

Votes:
YES:
NO:
ABSTAIN: 

# Integration System for Application and Runtimes should be represented as a separated types

Pros:
- IntegrationSystem that manages Runtimes AFAIK is RuntimeProvisioner which has completly different responsibilities comparing to Integration
System managing Applications
- if we have two separate types, we can strictly define permissions by using scopes, for example IntSystem for Runtimes cannot update Applications.
If we have only one type, then we need to check permissions internally in the business logic. 
Cons:

Votes:
YES:
NO:
ABSTAIN:

# Rename Integration System

Why?
IntegrationSystem name does not bring any information, how I will know from API it's purpose?

Proposals:
- ApplicationDelegate
- Operator
- IntegrationSystem (keep it as it is)


# Rename mutations create 

We do not create Runtime or Application we just register/add it to Compass. I don't like register, unregister because if we want to use the same 
methods for every type, it can looks strange `registerLabelDefinition` and `unregisterLabelDefinition`.

Proposals:
- keep as it is: Create/Delete
- Add/remove: 
- register/unregister:


# Generate mutations (generateClientCredentialsForApplication) replaced with request (requestClientCredentialsForApplication)

as an end-user, I don't have to know that for example Token is generated or not.

YES:
NO:
ABSTAIN:

# deleteSystemAuth... renamed to invalidateSystemAuth...

YES:
NO:
ABSTAIN:


# Designing the mutation payload

Here https://blog.apollographql.com/designing-graphql-mutations-e09de826ed97 I have found 
quite interesting approach and I would like to hear your opinion:

```
Just like when you design your input, nesting is a virtue for your GraphQL payload. Always create a custom object type for each of your mutations and then add any output you want as a field of that custom object type. This will allow you to add multiple outputs over time and metadata fields like clientMutationId or userErrors. Just like with inputs nesting is an investment that will pay off.
```

YES:
NO:
ABSTAIN:

**Comment by pkosiec** [comment]
# API should be always capitalized 

No: @pkosiec (Absolutely no - we should follow SDL convention. It will look weird. And I don't feel that always capitalizing API will bring consistency. It will be inconsistent to have some fields capitalized, and some not)

# Rename API and EventAPI to APIDefinitions and EventDefinitions

YES: @pkosiec makes sense

# Integration System for Application and Runtimes should be represented as a separated types

Additional cons:
- Integration Systems for Runtimes and Applications differ only with scopes. That's why it makes sense to have them both together as single entity, with multiple types (or even scopes for flexibility). (@pkosiec)

Votes:
NO: Let's have a single name for Integration Systems, but we can introduce types of them. Every type can have different scopes and that's the only difference

# Rename Integration System

- Operator: +1 @pkosiec

# Rename mutations create 

register/unregister:+1 (but only for Application, Runtime and Integration System)

# Generate mutations (generateClientCredentialsForApplication) replaced with request (requestClientCredentialsForApplication)

ABSTAIN: @pkosiec (We can change it, why not)

# deleteSystemAuth... renamed to invalidateSystemAuth...

NO: I don't like it, as SystemAuth is our entity. The main operation is deleting it. Sure, we invalidate the creds that are being deleted, but still, this is operation on SystemAuth, not on SystemAuth.value itself

# Designing the mutation payload

NO: I don't think we need that at all, It will only add boilerplate.

**Comment by dbadura** [comment]
We can consider changing inputs in mutations. 

In this [article](https://blog.apollographql.com/designing-graphql-mutations-e09de826ed97), the author mention that we should accept as input only 1 object with all properties. Doing it in this way, we can extend input without any major changes.

**Comment by KarolJaksik** [comment]
Please remember to remove the note at auto-app-management.md that mentions the changes are not yet implemented
