### ISSUE TITLE
API spec validation erroneous 

### ISSUE THREAD

**Issue by akrausesap** [kyma-incubator/compass#410]
**Description**

Although the below attached API specs seem valid they fail with error `Error: cannot recognize spec file.`

[API_OPLACCTGDOCITEMCUBE_SRV.yaml.zip](https://github.com/kyma-incubator/compass/files/3767326/API_OPLACCTGDOCITEMCUBE_SRV.yaml.zip)
[api-docs.json.zip](https://github.com/kyma-incubator/compass/files/3767329/api-docs.json.zip)

Kyma Version is 1.6 (upgraded from 1.5). Install via standard installer (image `eu.gcr.io/kyma-project/compass-ui:541467b2`)

**Expected result**

APIs are uploaded

**Actual result**
^
APIs fail 

**Steps to reproduce**

Add Specification to application

**Troubleshooting**

unknown

**Comment by PK85** [comment]
It's already fixed in the UI.
