### ISSUE TITLE
Scenario name validation

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#413]
**Description**

Scenario name validation should have rules that prevent creating scenarios with characters that may be potentially unsafe.

**Reasons**

That "///// . * * " scenario name is allowed and in the future could be a potential issue.

**Attachments**

Modify existing LabelDefinition for `scenarios` with regex for enum values. Update also schema that keeps `scenarios` valid.
```
{
  "items": {
    "enum": [
      "DEFAULT"
    ],
    "type": "string"
  },
  "minItems": 1,
  "type": "array",
  "uniqueItems": true
}
```

**Comment by crabtree** [comment]
Validation for enum values is done by the following regex `^[A-Za-z0-9]([-A-Za-z0-9\\s]*[A-Za-z0-9])$`
