### ISSUE TITLE
Update OathKeeper configuration for Director

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#416]
**Description**
- Do not expose tenant mapping handler for OAuth flow (for other flows it is already not exported)
- Expose GraphQL Playground for Director (GET request on Gateway's /director endpoint)
   -  for OAuth 2.0, certs and JWT hosts
   -  make it unsecured

**Reasons**
Tenant mapping handler is an internal endpoint.
GraphQL Playground is a very convenient tool for using Director, which has been available before introducing OathKeeper.

**Comment by PK85** [comment]
duplicated by: https://github.com/kyma-incubator/compass/issues/492
