### ISSUE TITLE
Add prow job that check if Compass is upgradable

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#431]
**Description**

If PR introduces changes to the chart, there should be a job that checks if we can upgrade from previously released compass version to version proposed in a PR. 
In the beginning, make this job optional.

**AC**

- Add prow job that check if Compass is upgradable
- make compass module as a default one in Kyma (update installation docs in kyma)
- Test two cases:
   - Kyma latest release -> last commit from PR
   - Previous commit -> last commit from PR (as a separate job, to check wether our test cluster is upgradable)

Blocked by: #684

**Comment by dbadura** [comment]
Check if chart is upgradable. 
We can use exisitng `e2e upgrade test` with modified list of components including compass and runtime agent.

**Comment by dbadura** [comment]
Current status:
Currently the job cannot pass upgrade, because Kyma Environment Broker is not upgradable,
Here is the issue: #684 

WE need to preprapre backup upgrade and probably turn on compass on Kyma.

**Comment by pkosiec** [comment]
To be continued in https://github.com/kyma-project/kyma/issues/7035
