### ISSUE TITLE
Block Integration System deletion, if there are any related apps

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#442]
**Description**
Modify `deleteIntegrationSystem` mutation: block deletion, if there are any applications with `integrationSystemID` created.

Modify existing integration test for integration system deletion.

For details, please see the proposal: https://github.com/kyma-incubator/compass/pull/359

**Reason**
See #428

**Comment by KarolJaksik** [comment]
It seems that there is no need for modifying the code since the database has appropriate constraints that restrict deleting the integration system. However there's a need to create a custom error that wraps the one from db.
