### ISSUE TITLE
New optional test for compass, runtime agent and compass-console

### ISSUE THREAD

**Issue by dbadura** [kyma-incubator/compass#449]
**Description**
Create new optional job to test integration between compass-director and runtime-agent.
UI will introduce smoke test in release 1.9
We can use the existing job in Kyma, (`pre-master-kyma-gke-compass-integration`).  

**Reasons**
This will help us to indicate that we introduced breaking change in our logic or api.

**AC**
* New job, run test of integration between compass-director and compass-agent
* New job is optional
* New job is launched when director introduce new change

**Useful links**
[Script kyma-gke-compass-integration.sh](https://github.com/kyma-project/test-infra/blob/0e287a9149b334850fd4dde48db846734606a640/prow/scripts/cluster-integration/kyma-gke-compass-integration.sh)

**Comment by PK85** [comment]
Runtime agent will be dead soon, we will use external System broker in the KYma runtime.
