### ISSUE TITLE
Provisioner registers runtimes in Compass Director

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#454]
**Description**

In the current state, Compass Provisioner accepts runtime ID as an argument for `provisionRuntime` mutation. In the desired flow user does not need to register given runtime in Director prior to provisioning it - this is Provisioner's responsibility.

[Director's mutation requires the following fields](https://github.com/kyma-incubator/compass/blob/master/components/director/pkg/graphql/schema.graphql):
```
scalar Labels

input RuntimeInput {
	name: String!
	description: String
	labels: Labels
}
```
Due to that, we will need to extend our API a bit.

Also, `deprovisionRuntime` should remove runtime from the registered list.

**Acceptance Criteria**
- [ ] ID parameter removed from `provisionRuntime` mutation
- [ ] Required fields added to the Provisioner API
- [ ] Runtime is registered by Provisioner when provisioning call is made
- [ ] Runtime is deregistered by Provisioner when de-provisioning call is made
- [ ] Consider whether `cleanupRuntimeData` mutation should be changed or not

**Comment by koala7659** [comment]
Decisions:

- Configuration for connectivity to Compass Director will be provided by helm chart.
- As a result of runtime registration Compass Director will provide runtime ID used later by provisioner.
- When Credentials to connect to Director cannot be obtained - Provisioner will still provision requested cluster but will skip registration step and it will generate used Runtime ID by itself.

**Comment by janmedrek** [comment]
We've decided to go with register scenario - if the Provisioner fails to connect to Director it will return an error. Skipping registration will be implemented later if required.
