### ISSUE TITLE
Eventing configuration (from Runtime) available to applications in the same scenario

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#458]
**Description**
From External Application point of view in some point of time after registration, it needs to receive Runtime specific information like: EventService URL. See what runtime Agent passes into compass: https://github.com/kyma-project/kyma/issues/5722 . We need a place in Application domain where External Application will monitor for that data.

**AC**
- runtime specific information is available under applications that are in the same scenario with runtime
- that information should be calculated from assigned runtimes (copying is not a good idea)
- we need to deal with many Runtimes assigned to application. Only one EventService URL could be used by external Application.
- add integration tests

**Implementation details proposal**
- https://github.com/kyma-incubator/compass/issues/458#issuecomment-554389299

**Comment by kfurgol** [comment]
One idea: ```
type Application {
 
 runtimesMetadata: [RuntimeMetadata!]!
 runtimeMetadata(id: ID!): RuntimeMetadata
}

type RuntimeMetadata {
 id: ID!
 labels: JSON!
}
```

**Comment by PK85** [comment]
Minimum (creds alreayd provided by pairing for apps to reach EventsServiceURL)
eventingConfiguration: {
URL: string
}

**Comment by pkosiec** [comment]
Suggested API:

```graphql

type Application {
	# (...)
	eventConfiguration: ApplicationEventConfiguration
}

type ApplicationEventConfiguration {
	defaultURL: String!
}
```

**Comment by pkosiec** [comment]
Assumption:
- Only one Runtime is default for eventing for Application (even when there are multiple scenarios)


Suggested API:

```graphql

type Application {
	# (...)
	eventConfiguration(): ApplicationEventConfiguration # Resolver
}

type ApplicationEventConfiguration {
	defaultURL: String!
}

setDefaultEventingForApplication(appID: String!, runtimeID: String!)

type Runtime {
  # (...)
  creationTimestamp: Timestamp!
  isDefaultEventing(appID: ID!): Boolean
  eventURL: String # populated from runtime/eventURL label
}
```

Resolver for eventConfiguration will work the following way:
- get all Runtimes within all scenarios of the given Application
- if there is a runtime with label `{appID}/defaultEventing`=`true`, return it
- if not: return runtime with earliest creationTimestamp

`setDefaultEventingForApplication` mutation works in the following way:
- get all runtimes  within all scenarios of the given Application
- if there is a runtime with label `{appID}/defaultEventing`=`true`, delete it
- set label `{appID}/defaultEventing`=`true` for new Runtime

**Comment by crabtree** [comment]
**Update:**

The Application type will support the configuration for eventing via `eventingConfiguration` field

```
type Application {
	# (...)
	eventingConfiguration: ApplicationEventingConfiguration
}

type ApplicationEventingConfiguration {
	defaultURL: String!
}
```

The resolver under the `eventingConfiguration` field will support the following algorithm:
- get all Runtimes from the scenarios assigned to the given Application
- filter the Runtimes with the label {appID}/defaultEventing=true, if there is a runtime found return its eventing URL
- if there is no runtime defined with label {appID}/defaultEventing=true then:
  - find the runtime with the oldest `creationTimestamp` 
  - label it with the label {appID}/defaultEventing=true
  - return the eventing URL assigned to that Runtime

Mutations `setDefaultEventingForApplication(appID: String!, runtimeID: String!)` and `deleteDefaultEventingForApplication(appID: String!)` can be called by the UI (user context) and Integration System. The scope required for those mutation is `eventing:manage`. 

When assigning new default eventing for the application the Runtime needs to be assigned in the same scenario as the Application.

Additional topics:
- UI should present which runtime is handling the events for the application within the scenario. This can be done by querying the runtime collection with the label {appID}/defaultEventing. This query should be done per application in the given scenario.
- UI should support setting new default eventing by calling the `setDefaultEventingForApplication(appID: String!, runtimeID: String!)` mutation.

**Comment by crabtree** [comment]
@pkosiec could you elaborate a bit more of possible use cases for the `isDefaultEventingForApplication(appID: ID!): Boolean` and `eventURL: String`?

**Comment by crabtree** [comment]
We should also consider providing additional documentation for the Application/Integration Systems regarding the things that should be monitored during the application lifecycle.
For now, we can identify topics like credentials requests and eventing configuration as the things that can be changed and application should be aware.

**Comment by pkosiec** [comment]
@crabtree 

> @pkosiec could you elaborate a bit more of possible use cases for the `isDefaultEventingForApplication(appID: ID!): Boolean` and `eventURL: String`?

Basically it is for API consistency: if we expose `defaultEventURL` for a given Application, populating it from Runtime label, it would be good to also expose this piece of information in Runtime itself: if the runtime is default for eventing, and which eventing URL it has.

I know these pieces of information are stored in labels, but if we create a layer of abstraction over these labels in one place, it makes sense to do it consistently across whole API - in this case, also in Runtimes.

Of course this is just my opinion, so I'm open to any discussion.

**Comment by crabtree** [comment]
@pkosiec OK, see your the point. From my perspective, it makes more sense to host the `eventingConfiguration` on the Application type only. My motivation is that it is not necessarily the desired solution to host the eventing on the runtimes. For now it is true but in the end, it may happen that the eventing will be some third-party solution not connected with the runtime instance.

Maybe to be more consistent we should add the whole nested type `eventingConfiguration` on the runtime as well. Then it will have the same, consistent API on the Application and the Runtime. In the end, if the Runtime will not host the eventing then querying this property will do the computation and return the eventing connected with given Runtime.

**Comment by pkosiec** [comment]
@crabtree Good point.

> Maybe to be more consistent we should add the whole nested type eventingConfiguration on the runtime as well. 

Sounds good to me 👍
