### ISSUE TITLE
Update existing create Application logic

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#460]
**Description**

- modify create Application method in Application service
     - check if integration system already exist while creating the application with `integrationSystemID`
     - create `integrationSystemID` (please suggest properkey name) label for Application. Do not validate it 
(do not create LabelDefinition manually)
     - pick one convention for label key naming 
- modify `updateApplication`
    - check if integration system already exist while updating the application with new `integrationSystemID`
    - update `integrationSystemID` label
 - remember about model validation from #255
- remember about integration tests

For details, please see the proposal: https://github.com/kyma-incubator/compass/pull/359

**Reason**
See #428

**Comment by KarolJaksik** [comment]
We have agreed upon the label key naming convention. The key names should be all lower case with dashes as separators, eg: `integration-system-id`
