### ISSUE TITLE
Return default event URL for default Kyma installation

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#471]
**Description**

In default Kyma installation (Compass and Runtime Agent in the same cluster), return a fixed eventing URL in new resolver for Application type. Pass the URL via environmental variable in Director deployment (in chart).

Suggested API:

```graphql
type Application {
	# (...)
	eventConfiguration: ApplicationEventConfiguration # Resolver
}

type ApplicationEventConfiguration {
	defaultURL: String!
}
```

Resolver for eventConfiguration will work the following way:
- if env with url is provided - return the value
- if it is not, return null for `eventConfiguration`

**Comment by aszecowka** [comment]
1. @pkosiec @PK85 how should I detect that there are Compass and Agent installed on the same cluster?

2. what is the correct value that should be returned? 

Is it `--gatewayBaseURL=https://gateway.{{ .Values.global.ingress.domainName }}"`

**Comment by PK85** [comment]
1) https://github.com/kyma-project/kyma/blob/master/resources/compass/values.yaml#L44
2) Check what agent sets in the runtime as a label for eventServiceURL. And yes, it's a matter of {{domain}} then
