### ISSUE TITLE
Create proposal for simplify usage of Compass API for paired Application

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#481]
**Description**

**Note:** Before starting implementation, investigate how others do that. Prepare document about it (max 1 MD!) - @kfurgol 

Let assume the following scenario:
1. The user creates in UI application
2. The user generates a one-time token and provides it to application
3. The application generates certificate used for communication with Director
4. The application wants to add API using the following mutation:
```
addAPI(applicationID: ID!, in: APIDefinitionInput!): APIDefinition!
```

The drawback in this approach is the following: Application has to know it's own `applicationID` which is inconvenient. 
Compass can distinguish Application on the basis of information stored in the certificate.

**AC**
- allow external application to work with its own application definition without a need to provide applicationId (modify all Application related queries and mutations)
- add a comment with reason to all Application operations that have optional ApplicationID

**Potential Solution**
All operations related to Application in compass should have applicationId as optional input parameter. The usage of them will be:
- if credential belongs to Application, input applicationID is not required (can be provided and we will just check if they are the same)
- if credential belongs to IntegrationSystem, then IS will of course use applicationId cause it can manage many of them

**Comment by aszecowka** [comment]
To consider another use case:
- when integration system registers application template or creates Application, he also needs to provide integrationSystemID

**Comment by PK85** [comment]
Regarding  usecase reported by @aszecowka . Yes, we need to handle that better and not force IS to set ISid.
