### ISSUE TITLE
Service Class from APIs defined in the Compass has empty Provider field

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#486]
**Problem**: How I can provide information that given API is provided by given company?

So far, runtime agent has following implementation:
```
ProviderDisplayName: "", // not available in the Director's API
```
kyma/components/compass-runtime-agent/internal/kyma/applications/converter.go:107

Information about the provider should be stored as a root attribute of the Application type. 

**AC**
- check how provider is implmeneted in the ApplicationCR
- copy solution to compass Application
- agent fetch that information and sets provider in the ApplicationCR
- UI can display the provider value (populate provider in runtime agent)
- modify integration tests

**Comment by dbadura** [comment]
reestimated from 2 to 5 (bump in kyma, changes in runtimeagent and in console UI)
