### ISSUE TITLE
Brocken UI Icons?

### ISSUE THREAD

**Issue by tricky42** [kyma-incubator/compass#489]
Browsing the Compass UI there are several places where broken special characters are displayed. In the Dev Tools you can see that the browser had problems to download a font.....

<img width="774" alt="Screen Shot 2019-11-21 at 14 24 54" src="https://user-images.githubusercontent.com/402282/69342219-57a9c800-0c6b-11ea-8b1a-4fb17518cfb8.png">

I also attached the content of the font which the browser tries to download, doesn't look like a font. 
[output.txt](https://github.com/kyma-incubator/compass/files/3874885/output.txt)

**Comment by kwiatekus** [comment]
will be addressed https://github.com/kyma-project/console/issues/1408
