### ISSUE TITLE
Use single gateway host for jwt and oauth2 access token authentication

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#491]
**Description**
Because of oathkeeper lack of feature we have 3 hosts in compass per authenticator, see details: https://github.com/kyma-incubator/compass#usage

As feature has been implemented we need one host for for jwt and oauth2 flows:
- use https://compass-gateway.{domain} for them
- still we need to keep https://compass-gateway-mtls.{domain} separate cause it's not using oath keeper authenitcator

**AC**
- implement a change, update test and documentation

**Comment by KarolJaksik** [comment]
It seems that currently we still can't use one host for the two methods of authentication. The goal is to use different tokens in the same `Authorization` header. We will come back to it in the future.

**Comment by PK85** [comment]
invalid.
