### ISSUE TITLE
Add raw json config to OneTimeToken type in director

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#494]
**Description**

We need a one attribute under OneTimeToken that could be copy pasted to Application.

**Reasons**

Right now user has two steps to do:
- copy and paste URL
- copy and paste token

This ticket will allow user to copy paste just once.

**AC**
- extends OneTimeToken structure with raw attribute, that contains a json with URL and token.
- remember about integration tests
- take into account @ormos comments

**Comment by ormos** [comment]
This enhancement is focusing on enhancing the user experience when doing the manual one-time-token flow. But be aware that the exchange of the one-time-token will not always be through copy/paste in one system. Administrators might exchange the token via email or messenger with their colleagues. So we should really encode the json structure (e.g. base64) to avoid any problems when using different transport mechanisms.

**Comment by ormos** [comment]
We should also design this in a way that an extension system, is also able to add additional information which should be transported to the target system. So probably the json structure should be extensible for data from an extension system before encoding.
