### ISSUE TITLE
Document and verify basic compass scenarios

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/compass#496]
**Description**

Document the following scenarios:
- registration of application 
- registration of application by integration service
- registration of runtime
- grouping applications and runtime in the scenario

Each scenario should contain a sequence of API calls and some visualization (diagram). Scenarios should be verified by end2end tests (integration tests).

**Reasons**

It is not easy to explain the compass mission and basic flows. Some of the flows are not fully implemented and it is not visible in the project documentation.

**Comment by crabtree** [comment]
Registration of application and registration of application by integration service will be covered via issue #415, the proposal for those scenarios is on PR #450.
