### ISSUE TITLE
Fix the Labels scalar in graphql schema

### ISSUE THREAD

**Issue by kjaksik** [kyma-incubator/compass#498]
**Description**

Think of a way how to handle the `Labels` scalar used in `ApplicationCreateInput` type so that it will accpet keys with characters other than alphanumeric.

**Reasons**

The label naming convention that we agreed upon uses dashes as separators. Graphql schema accepts only alphanumeric characters in the `Name` type.

**Comment by KarolJaksik** [comment]
Please remember to update the documentation according to our proposed fix

**Comment by PK85** [comment]
closing, invalid.
