### ISSUE TITLE
Use MILV for Markdown link validation

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#50]
**Description**

Use MILV for link validation in docs. Run the tool as CI step for all changed Markdown files. 

**Reasons**
- we will make sure that all links are valid
- we have to unify approach if we want to move to `kyma-project` organization

**Comment by dbadura** [comment]
[MILV on Github](https://github.com/magicmatatjahu/milv)

**Comment by PK85** [comment]
wont fix.
