### ISSUE TITLE
Cleanup Compass components structure

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#504]
Currently, in `components` directory, we have the following items:
- connector
- director
- gateway
- healthchecker
- provisioner
- schema-migrator

In the near future, kyma-environment-broker will be added.
A similar situation is with the naming of tests:
- connector-tests
- end-to-end 
- provisioner-tests

Drawbacks of current approach is the following: we keep together unrelated components:
- schema-migrator is responsible for director schema migrations
- gateway proxies traffic only to connector and director

Proposed solution:
- rename `end-to-end` tests to `director-tests`
- consider removing `gateway` component - currently, it does not bring any value
- consider removing `healthchecker` component
- consider moving `schema-migrator` inside director
- divide components into 2 sub-groups: provisioning (provisioner, kyma-environment-broker) and management (director, connector?)

**Comment by crabtree** [comment]
I would also consider splitting the e2e directory into two, one with actual e2e tests and one with director tests

**Comment by Szymongib** [comment]
> divide components into 2 sub-groups: provisioning (provisioner, kyma-environment-broker) and management (director, connector?)

What is the reasoning behind that? I am not convinced if it provides much value and in case if there will be a new component that touches on both of those categories it will create more confusion.
