### ISSUE TITLE
Make Label related mutations use unique input type

### ISSUE THREAD

**Issue by tgorgol** [kyma-incubator/compass#515]
**Description**

Similarly to other mutations that create/update resources Labels should use single, unique input argument that can be easily validated.

Currently Labels set with those mutations are temporarily validated in resolvers, that validation should be done with `@validate` directive.

Current mutations:
```
setRuntimeLabel(runtimeID: ID!, key: String!, value: Any!): Label!
setApplicationLabel(applicationID: ID!, key: String!, value: Any!): Label!
```

Proposed mutations:
```
setRuntimeLabel(runtimeID: ID!, in: LabelInput! @validate): Label!
setApplicationLabel(applicationID: ID!, in: LabelInput! @validate): Label!
```

**Reasons**

Single, unique input argument allows us to easily validate and extend mutation, this is important in version-less schema.

**Comment by pkosiec** [comment]
@tgorgol Can we implement it right now? What is the status of directives support in gqlgen?
