### ISSUE TITLE
[Director] Application owner should be able to update status.

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#517]
**Description**

Application provides the status property but it cannot be set via the GraphQL level. We should think how the system can impact the application status. Whether it is a direct update like other application properties or should we consider providing some event-like handling to set this property. Setting this field to `READY` or `FAILED` can be done probably only by Application itself, or Integration System.
 
Create a proposal how to do it.

**Comment by pkosiec** [comment]
It is already done: https://github.com/kyma-incubator/compass/pull/1260
