### ISSUE TITLE
De-provisioning internal server error

### ISSUE THREAD

**Issue by andreaAlkalay** [kyma-incubator/compass#522]
In the creation of a kyma cluster we have several steps. 
In case a step prior to the provision call fails the de-provision call returns 500 Internal server error.

If the environment instance-id does not exist shouldn't you return a 404 or 200?

Here is a sample:
Url: https://kyma-env-broker.compass-stage.compass.yaas.io/v2/service_instances/54B95508-5B80-437A-A675-3204F7CAA027?service_id=47c9dcbf-ff30-448e-ab36-d3bad66ba281&plan_id=cf3698e9-8833-4c10-8213-c84d2438da07&accepts_incomplete=true
Method: DELETE
Body: 
============= End Request =============
============= Begin Response =============
Status Code: 500
Status Text: Internal Server Error

Thanks,
Andrea.

**Comment by piotrmiskiewicz** [comment]
The OSB API defines Http 410 GONE in case the instance was already deprovisioned.

**Comment by piotrmiskiewicz** [comment]
The scenario withdeprovisioning of failed instance (or not existing instance) must be tested and checked if it is consistent with OSB API
