### ISSUE TITLE
Timeout waiting for condition

### ISSUE THREAD

**Issue by andreaAlkalay** [kyma-incubator/compass#523]
Hi,

The provisioning of Kyma cluster fails with the following:
https://kyma-env-broker.compass-stage.compass.yaas.io/v2/service_instances/5D9CC919-FB77-4845-BC3E-C08404127FD6/last_operation?service_id=47c9dcbf-ff30-448e-ab36-d3bad66ba281&plan_id=cf3698e9-8833-4c10-8213-c84d2438da07&operation=5a079498-8fde-48d2-b731-03ecf134a9ef

Returns 200 OK with 
{
    "state": "failed",
    "description": "timeout waiting for condition"
}

Can you have a look?

Thanks,
Andrea.

**Comment by piotrmiskiewicz** [comment]
The provisioning failed because of an infrastructure problem, which may happen. In such case the broker returns such response.

**Comment by pbochynski** [comment]
@piotrmiskiewicz and @andreaAlkalay - I understand that it was a problem that is not persistent. I just want to confirm with you, that it works in most cases.
