### ISSUE TITLE
Unable to provision cluster

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-incubator/compass#528]
**Description**

The current  version of Provisioner uses outdated hydroform, which is unable to create a cluster in Gardener.

**Expected result**

Provisioner is able to create cluster on Gerdener

**Comment by janmedrek** [comment]
Can you please confirm if the issue is still present?
If yes - we would need more details to investigate: versions of components, logs, requests and error message that was returned by Provisioner.
