### ISSUE TITLE
Kyma is not returning dashboardUrl as environment data

### ISSUE THREAD

**Issue by shaiembon** [kyma-incubator/compass#536]
Hi
Kyma response doesn't contain the dashboardUrl needed in order to display the user in cockpit a link to the Kyma environment.

Thanks,

Shai Embon

**Comment by piotrmiskiewicz** [comment]
Kyma Environment Service Broker must get the dashboard URL from the Director when the instance is ready.

**Comment by piotrmiskiewicz** [comment]
The dashboard url will be available after the provisioning is done (and succeeded), on the fetching instance operation: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#fetching-a-service-instance

**Comment by polskikiel** [comment]
It will be resolved within this issue: https://github.com/kyma-incubator/compass/issues/600
