### ISSUE TITLE
Update buildpack in Provisioner

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#545]
**Description**

Compass Provisioner requires Go 1.13, but there is no Golang buildpack with Go 1.13 and all helper tools like `errcheck` therefor those checks are disabled. 

**Acceptance:**
- Proper buildpack created (Golang `buildpack-toolbox` with go 1.13)
- Buildpack used in Compass Provisioner component
- `errcheck` enabled in Makefile

**Comment by janmedrek** [comment]
Moving to the KCP repo: https://github.com/kyma-incubator/compass/issues/545
