### ISSUE TITLE
Compass e2e tests should use Director code from repository, not from vendor

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#578]
**Description**

Let assume a situation that you have to modify tests and director in the same PR - then it is cumbersome, because in toml you need to define that you depend on forked director repository.
If you depend on forked repository, you have to create another PR with cleaning up dependencies in TOML file.
Thanks to removing vendoring Director, the development will be simpler and faster.

**AC**
- Compass e2e tests should use Director code from repository, not from vendor

**Comment by dbadura** [comment]
In every change in director, remember to execute prow job for building tests image.
