### ISSUE TITLE
Kyma Environment Broker returns SKR console URL to ERS

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#585]
**Description**
This issue is about to make KEB to work E2E with Service Catalog and Provisioner API. Broker gets the Director Runtime ID from Provisioner. Then tracks Runtime definition and when available returns Kyma Runtime console URL to Service Catalog and marks provisioning operation as Finished.

**AC**
- broker has persistence, restart of the component must not cause issues
- take care about id mapping between ERS and RuntimeID
- check in compass Director if runtimeID has consoleURL information. When provided returns to ERS
  - during compass installation create integration system and its credentials pass to KEB and then fetch runtime data (reuse provisioner configuration to get IS,  generalise that and put in the main chart. That will create two IS for Provisioner and KEB )
- pass external Tenant ID (aka globalAccount) to provisioner
- documentation about what is exposed by broker and how it works

**Comment by piotrmiskiewicz** [comment]
Current status:
 * the provisioner client is updated to the new contract (by a feature flag) - the code is merged but not used in the cluster. The contract is not tested because we are waiting for the deployed Provisioner with new contract

**Comment by piotrmiskiewicz** [comment]
The full e2e story described above can be tested when the agent saves the dashboard URL in the director. This will be done when the PR https://github.com/kyma-incubator/compass/pull/693 is merged

**Comment by pbochynski** [comment]
Is it done? Can we close it?

**Comment by polskikiel** [comment]
@PK85 The story is completed but we couldn't test it on the dev cluster due to its instability. But we tested it on our cluster and it works fine.

**Comment by polskikiel** [comment]
It was implemented and tested long time ago, closing.
