### ISSUE TITLE
Cluster provisioning failure

### ISSUE THREAD

**Issue by andreaAlkalay** [kyma-incubator/compass#594]
Hi,

We are getting the following error:

Cluster provisioning failed: unable to provision gardener cluster: unable to provision cluster: 1 error occurred:
	* gardener_shoot.test_cluster: 1 error occurred:
	* gardener_shoot.test_cluster: shoots.garden.sapcloud.io "andrea-subaccou" is forbidden: secretbinding.garden.sapcloud.io "trial-secret-aws" not found

Can you check this?
Thanks,
Andrea.

**Comment by piotrmiskiewicz** [comment]
Currently, the AWS is not supported yet. We are planning to offer only Azure. The GCP and AWS will be available later. We haven't setup dedicated account in AWS.
