### ISSUE TITLE
Handle the Dashboard URL in KEB

### ISSUE THREAD

**Issue by polskikiel** [kyma-incubator/compass#600]
**Description**

After the director API will be extended to return the dashboard URL of the provisioned Runtime, the KEB will be able to request and pass that information to the ERS.

AC:
- implement the fetch of the dashboard URL from director API
- expose that data to ERS

**Reasons**

This story will end the e2e scenario with KEB.

**Attachments**

Director API dashboard URL implementation PR:  []

**Comment by piotrmiskiewicz** [comment]
We do not need oauth, just direct call to the Director.
