### ISSUE TITLE
Provisioner should update status during installation

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#615]
**Description**

The current implementation sets provisioning operation status when operation starts and finishes (either successfully or with error). Provisioner should also update status information when installing Kyma. 

**Reasons**
The user stores operation-id provided by provisionRuntime mutation in order to check asynchronous operation status. The status information should be as descriptive as possible and provide information on the actual state.

**Comment by janmedrek** [comment]
Moving to the KCP repo: https://github.com/kyma-project/control-plane/issues/89
