### ISSUE TITLE
Agent MVP implementation

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#62]
**Description**
Implement Agent and fulfill the contract between Agent and Director/Connector.

**AC**
- Add the Agent component into the Compass, in addition:
  - helm chart update
  - release pipeline
- Keep in mind that all calls can fail so retries are mandatory
- The agent takes configuration from Compass and manages Application CRs and all their dependent objects
  - more or less behave identically as we have right now in application-registry component in kyma
  - Compass exposes specs via blobs, agent takes it and stores in minion internally in runtime
- The agent periodically applies changes of the configuration from Compass on to the runtime.

Stretch (depends on the status of connector migrated to compass):
- The agent is able to establish a trusted relation between runtime and Compass based on client certificates
- The agent is able to renew the client certificate for the runtime before it expires

**Comment by crabtree** [comment]
I split this issue into smaller ones as this covers too much implementation details and is hard to estimate aa a whole. Pleas follow the Epic.
