### ISSUE TITLE
Error messages in Provisioner may leak implementation details

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#639]
**Description**

Error messages returned to the user are built by wrapping errors from internal components (database handling code, Hydroform/Terraform)  so that they can leak some implementation details. 

**Expected result**

Error message should not contain implementation details and be descriptive to the user. 

**Actual result**

Messages include errors returned from database driver or Terraform. 

**Steps to reproduce**

Call runtimeOperationStatus query with an id that is not a valid UUID. The result will be as follows:
"Failed to get <id> operation: pq: invalid input syntax for type uuid: \"<id>"

In this case the message should tell the user that they passed incorrect value. Instead it says that postgres database driver returned error.

**Comment by janmedrek** [comment]
DB driver should be excluded from error message building mechanisms.

**Comment by janmedrek** [comment]
Moving to the KCP repo: https://github.com/kyma-project/control-plane/issues/86
