### ISSUE TITLE
Consider validating component list in Provisioner

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#640]
**Description**

User specifies the list of components to be installed. In case a non-existent component name was provided (e.g. typo) the installation process will timeout as the Kyma Installer won't be able to complete. Consider validating component names specified before provisioning operation starts.

**Reasons**

From the user's perspective it is important to quickly find a mistake they made. Introducing validations on components list will make feedback loop significantly shorter.

**Comment by janmedrek** [comment]
This will be solved as a part of: https://github.com/kyma-incubator/compass/issues/400
