### ISSUE TITLE
Too strict input data validation for APIDefinitionInput

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#652]
According to [validation rules](https://github.com/kyma-incubator/compass/blob/master/docs/compass/03-input-validation.md)
APIDefinitionInput.name has the following constraints:
>  Up to 36 characters long. Cannot start with digit. The characters allowed in names are: digits (0-9), lower case letters (a-z),-, and .. Based on Kubernetes resource name format.

Because this name is presented in the UI, I would like to use uppercase and spaces.
Please rethink validation rules for other types.

**AC**
- see my investigation and confirm that with codeowners of the agent. If we don't want to add everywhere displayNames, we should relax a validation for name, from all places where validation was applied

**Comment by pkosiec** [comment]
Hmm, maybe we could add another field `displayName`. Our validation rules for names are the same as Kubernetes + additional ones, required for ServiceClass name construction on Runtime.

It would make sense to have display name, as on ServiceClass we also have this field.

**Comment by a-thaler** [comment]
The error message for a name like "Schools API" is:

`GraphQL error: validation error for type APIDefinitionInput: name: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')].'`

This is even misleading as it talks about domains.

**Comment by PK85** [comment]
ok, I've checked how compass-runtime-agent creates Application CR from director applications.

Application CR has two fields:
```
displayName: aaa-hello-aaa
name: aaa-hello-aaa-6b030
```
Director Application API was: aaa-hello-aaa. 
As we see, agent takes Director name for displayName 1:1, and also converts name to name with some rules and makes it unique.
