### ISSUE TITLE
Pass query parameters to the hydrator

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#660]
**Description**
We need a way to Pass query parameters to the hydrator. 

See root issue: https://github.com/ory/oathkeeper/issues/339

**AC**
- contribute and use in Kyma

**Comment by pkosiec** [comment]
@crabtree what value this feature bring for us? Do you remember what's the use case for this feature for us?

**Comment by crabtree** [comment]
@pkosiec we need this feature to be able to remove this envoy filter https://github.com/kyma-incubator/compass/blob/master/chart/compass/templates/rewrite-token-filter.yaml
