### ISSUE TITLE
Backup for Runtimes with Compass Provisioner

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#667]
**Description**

The goal of this task is to have the first (simplest) version of manually triggered backup for Kyma runtimes.

The current assumptions are:
- we are using Velero
- backup is done automatically - schedule is yet to be defined
- there is no "restore" endpoint (for now), any action that involves creating a cluster from backed up resources is done manually

**Acceptance Criteria**

- short document on how the backup is handled in Provisioner
- the minimum version is to trigger the backup before upgrade action
- define acceptance test scenario

**Comment by a-thaler** [comment]
As part of https://github.com/kyma-incubator/compass/issues/751 a scheduled backup will be activated out-of-the box using that installer settings: https://github.com/kyma-project/kyma/blob/343a3c06966c7ffdee4cf7f018a74f4f93100540/resources/backup/values.yaml#L208

With that there is no additional step needed to have a scheduled backup running and this ticket might be focused on triggering manual backups maybe?
