### ISSUE TITLE
Use central postgreSQL for management Plane ORY

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#674]
**Description**

After Integration System registers in the Director, it sometimes loses the ability to fetch OAuth Bearer Token for itself due to 'unexisting client credentials' errors.

Currently, the Director uses direct calls as a way to create Hydra clients, most probably they are not persisted through pod restarts. This affects all clients that are not created via Custom Resources when no database connection for Hydra is present.

**Expected result**

OAuth clients are persisted through Hydra pod restarts.

**Actual result**

Pod restart results in OAuth clients for Integration Systems being deleted.

**Steps to reproduce**

1. Register Integration System in Compass Director
1. Kill Hydra pod
1. Try to fetch token for registered Integration System's credentials

**AC**
- turn on persistance on ORY hydra in central compass mode. See a closed ticket that allows that:  kyma-project/kyma#6812
- refresh credentials for existing integration systems

**Comment by piotrmsc** [comment]
Persistence was added in https://github.com/kyma-project/kyma/pull/6812. Enable it by default if required

**Comment by janmedrek** [comment]
@PK85 please decide on how this should be handled from the Director's point of view - I would suggest enabling persistence by default if compass is installed on the cluster.

**Comment by PK85** [comment]
@piotrmsc please point to a ticket with local proxy for GCP

**Comment by piotrmsc** [comment]
@PK85 https://github.com/kyma-project/kyma/issues/7053

**Comment by kfurgol** [comment]
After adding [overrides](https://github.com/kyma-project/kyma/blob/9ecc66fdd0ebc7d4fdb4df90546ed85d3a0355b2/installation/resources/installer-config-production.yaml.tpl#L10) on local installation with Compass everything worked correctly with Postgres, although there is no persistence at all without the database.  Also, the issue is blocked by [#7053](https://github.com/kyma-project/kyma/issues/7053)
