### ISSUE TITLE
Create a common package with shared sources

### ISSUE THREAD

**Issue by polskikiel** [kyma-incubator/compass#681]
**Description**

In our projects, we use the same clients to authorize with the Director or to connect/test the database. To prevent any inaccuracies in the future we should use the same codebase for them.

Currently copied packages in KEB are:
- oauth client
- provisioner client
- postgresql initialization
- postgresql test utils

**Reasons**

Duplicated code is never a good practice.

**Comment by PK85** [comment]
Close it for now. We will back to the topic after compass repository split.
