### ISSUE TITLE
KEB should install all required resources on cluster automatically

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/compass#686]
**Description**

We need to add missing resources like ingress and missing credentials for KEB like gardener secrets in helm chart, so cluster that will be created always is properly set up and no manual actions are required.

AC:
- no manual actions are needed to set up the KEB when installing on the cluster from the official chart

**Comment by piotrmiskiewicz** [comment]
Define ory rule for KEB, still use Basic Auth as before

**Comment by piotrmiskiewicz** [comment]
- [x] VirtualService and Ory rule
- [ ] overrides for secret names
- [ ] create gardener secret and broker secret in dev cluster (manual action)

**Comment by piotrmiskiewicz** [comment]
manual steps:
1. create secret gardener-canary-gopher, service-manager-creds, compass-kyma-environment-broker
2. Setup overrides and proper values in ConfigMap and Secret:
Secret:
global.kyma-environment-broker.broker.password
global.kyma-environment-broker.serviceManager.password
global.kyma-environment-broker.serviceManager.url
global.kyma-environment-broker.serviceManager.username
ConfigMap:
global.kyma-environment-broker.azure.secretName:
global.kyma-environment-broker.gcp.secretName: 
global.kyma-environment-broker.provisioner.gardener.secretName:
