### ISSUE TITLE
The call to Directors fails when the cluster is not "warm-up"

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/compass#688]
**Description**

When the MPS compass is provisioned and not used for some time, then the first calls always fail with such error:
```
{
    "description": "Failed to provision Runtime: Failed to execute request: graphql: Failed to register runtime in Director. Request failed: decoding response: json: cannot unmarshal string into Go struct field graphResponse.Errors of type graphql.graphErr"
}
```

The second call will be succeded but after some time when you do not use the MPS cluster, the problem will reoccur.

**AC:**
- The is no need to "warm-up" the cluster to have a successed calls

**Comment by mszostok** [comment]
The underlying problem is detected in director:
```
time="2020-01-21T08:36:59Z" level=error msg="while opening the db transaction: write tcp 10.52.8.14:48518->10.55.254.89:5432: write: broken pipe" func="github.com/kyma-incubator/compass/components/director/internal/tenantmapping.(*Handler).logError" file="/go/src/github.com/kyma-incubator/compass/components/director/internal/tenantmapping/handler.go:118" component=tenant-mapping-handle
```

full logs:
[director.log.zip](https://github.com/kyma-incubator/compass/files/4090658/director.log.zip)

**Comment by pkosiec** [comment]
@crabtree found an interesting issue - it may be related: https://github.com/istio/istio/issues/17139

**Comment by polskikiel** [comment]
In [this](https://github.com/kyma-incubator/compass/pull/697) PR, we added retries to our calls to the database to fix this. It's a temporary solution.

**Comment by PK85** [comment]
Timeboxed: 3SP. Contact @piotrmiskiewicz to get details what was set for KEB
