### ISSUE TITLE
Introduce a displayName attribute for Application Template placeholder

### ISSUE THREAD

**Issue by kwiatekus** [kyma-incubator/compass#721]
**Description**

Introduce a mandatory `displayName` attribute for AppTemplate placeholder, that could serve as an input label in the UI.

Currently, there is only :
 * `name` - which is rather technical and not suitable for UI. It is used to identify the placeholder in the template and to replace it with the actual value.
* `description` - it is optional, so rendering a field label based on that its risky. It may be used to render an optional [html input placeholder](https://www.w3schools.com/tags/att_input_placeholder.asp) in the ui 

**Expected result**

<img width="1488" alt="Screen Shot 2020-01-24 at 14 33 14" src="https://user-images.githubusercontent.com/6783567/73072932-86842a80-3eb6-11ea-8ef6-c85c4277e93f.png">

**Comment by kwiatekus** [comment]
https://github.com/kyma-project/console/pull/1513#pullrequestreview-343312461

**Comment by PK85** [comment]
@kwiatekus right now name has relaxed validation, where you can use human readable names with whitespaces etc. Name is still unique. 

Closing that issue. Dont hesitate to contact me if needed.
