### ISSUE TITLE
Runtime Agent serves as proxy to the Director

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#752]
**Description**

There are some cases where services other than Runtime Agent require information that is stored within the Compass Director and can only be fetched via the use of API. We would like to provide a way for those services to make use of connection established by Runtime Agent.

**Acceptance Criteria**
- Runtime Agent has a separate port that serves as a proxy to the MPS
- The service is available only internally and the privileges are narrowed down by Istio RBAC rules

**Comment by mszostok** [comment]
Currently we having problem with compass and runtime connections because of that I'm not able o test the current implmementation.

**Comment by mszostok** [comment]
**Description**

- [x] Add Director proxy in Runtime Agent
- [x] Simplify`main.go` by adding **ExitOnError**
- [x] Simply the startup of components (this is already implemented no need to do it by custom logic), see logger service changes.
- [x] Remove redundant comments in main -`Info`log statement is enough
- [x] Execute `make fmt-local` and `make imports-local`
- [x] Change channel from `bool` to `struct` which [occupies zero bytes of storage](https://dave.cheney.net/2014/03/25/the-empty-struct) (there was no need to use the bool channel).
- [x] Change build pack version to use Go 1.13 version (in 1.12 type *http.Transport does not have Clone method) btw. the Dockerfile already uses 1.13 for building binary so test should also be executed against that version
- [x] To be discussed: Is there a bug where the input certs are outdated?
--PR: https://github.com/kyma-project/kyma/pull/7504

Istio RBAC will be added in this task: https://github.com/kyma-project/kyma/issues/7062

**Comment by mszostok** [comment]
In this task the Proxy to Director was implemented and it is already available on runtime agent on port 8081. 

Istio RBAC will be added in this task: https://github.com/kyma-project/kyma/issues/7062
