### ISSUE TITLE
Fetching operation status does not validate Tenant

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#763]
**Description**

Tenant is not validated while fetching operation status. Clusters are assigned to a specific tenant and the `Tenant` header matching the Tenant in the database is required.

**Expected result**

Tenant cannot fetch operations started by other tenants.

**Actual result**

All operation statuses can be fetched providing any tenant.

**Comment by Maladie** [comment]
This will be fixed with #1107
