### ISSUE TITLE
Connectivity Adapter doesn't call Director to obtain Application name and Events base URL on signingRequest/info endpoint

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/compass#774]
**Description**

signingRequest/info endpoint doesn't return correct paths to Event Service and Application Registry. According to [Kyma documentation](https://github.com/kyma-project/kyma/blob/master/docs/application-connector/08-02-get-client-certificate.md), management/info is the recommended way for obtaining services urls. But there could be clients that do not adhere to this guidelines and use signingRequest/info to get urls fore accessing Application Registry and Event Service.  

**Expected result**

Application Registry and Event Service urls returned from signingRequest/info are the same as urls returned from management/info. Mind that signingRequests/info is secured with token so in order to call Director, Connectivity Adapter should be registered as an integration system.
 

**Actual result**

```
{
    "api": {
        "certificatesUrl": "https://adapter-gateway.kyma.local/v1/applications/certificates",
        "eventsInfoUrl": "/<system Auth ID>/v1/events/subscribed",
        "eventsUrl": "/<system Auth ID>/v1/events",
        "infoUrl": "https://adapter-gateway-mtls.kyma.local/v1/applications/management/info",
        "metadataUrl": "https://adapter-gateway-mtls.kyma.local/<system Auth ID>/v1/metadata/services"
    },
    "certificate": {
        "extensions": "",
        "key-algorithm": "rsa2048",
        "subject": "O=Org,OU=OrgUnit,L=locality,ST=province,C=DE,CN=<system Auth ID>"
    },
    "csrUrl": "https://adapter-gateway.kyma.local/v1/applications/certificates?token=<token>"
}
```

Please notice, that metadataUrl, eventsUrl and eventsInfo url contain system auth ID whereas the application name should be returned. Additionally eventsUrl and eventsInfo base path is empty.

**Steps to reproduce**

1) Generated token from UI
2) Call the following endpoint with the token
`curl https://adapter-gateway.kyma.local/v1/applications/signingRequests/info\?token`

**Comment by franpog859** [comment]
Before closing the issue make sure that both the implementation and the documentation are provided!
