### ISSUE TITLE
Replace satori go uuid library

### ISSUE THREAD

**Issue by jose-cortina** [kyma-incubator/compass#791]
**Description**

The library github.com/satori/go.uuid is outdated and has security vulnerabilities. It must be replaced by an alternative or own code.

Whitesource report: https://saas.whitesourcesoftware.com/Wss/WSS.html#!libraryDetails;uuid=1b43d104-5efd-402c-8e13-f6aeef9b7b18;project=1802214;orgToken=74cbbb27-f32c-474e-bb6b-d99fbffddee4
Code search: https://github.com/kyma-incubator/compass/search?q=satori&unscoped_q=satori

See also: https://github.com/kyma-project/kyma/issues/2883

**Expected result**

Library is not used.

**Comment by janmedrek** [comment]
We cannot remove satori as Gardener libraries are using it, and we directly depend on those libs:
```
> go mod graph | grep satori
github.com/testcontainers/testcontainers-go@v0.3.1 github.com/satori/go.uuid@v1.2.0
github.com/hashicorp/terraform@v0.12.2 github.com/satori/go.uuid@v1.2.0
github.com/gardener/etcd-backup-restore@v0.0.0-20190807103447-4c8bc2972b60 github.com/satori/go.uuid@v1.2.0
github.com/dylanmei/winrmtest@v0.0.0-20190225150635-99b7fe2fddf1 github.com/satori/go.uuid@v1.2.0
github.com/gardener/gardener@v0.0.0-20190830053951-194cf8abb797 github.com/satori/go.uuid@v1.2.0
github.com/gardener/machine-controller-manager@v0.0.0-20191118095523-e30355bc7945 github.com/satori/go.uuid@v1.2.0
github.com/aliyun/alibaba-cloud-sdk-go@v0.0.0-20190723075400-e63e3f9dd712 github.com/satori/go.uuid@v1.2.0
github.com/gardener/gardener@v0.0.0-20190812144748-dec8f3c7f288 github.com/satori/go.uuid@v1.2.0
```
