### ISSUE TITLE
KEB  - Provisioner contract test

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-incubator/compass#799]
**Description**

Implement an integration test which checks the contract between Kyma Environment Broker and Provisioner. 

AC:
 - the test is implemented in `tests/kyma-environment-broker`
 - the test is run together with other tests in `compass-integration` prow job
 - the test should trigger KEB to call Provisioner and expects operation ID, then check operation status and expects failed status

**Comment by PK85** [comment]
Closing. We have e2e for that now.
