### ISSUE TITLE
Automatic update of Compass Chart in Kyma repository

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/compass#832]
Currently, developers work in the following scenario:
- introduce some changes in Compass: change code of components, modify charts(for example use PR images in charts)
- after merging to the master branch of Compass repository, create another PR for Kyma repository to copy recent changes. When copying changes, we replace PR images with images generated by post-submit jobs.

This approach has some drawbacks:
- currently, many teams are working concurrently on Compass so if someone forgot to bump version on Kyma, a developer has to copy changes from different components and from many commits
- there are small differences between the version of the chart in kyma and compass repository, so a dev who copy chart has to ensure that he does not override them

Possible solution:
- create a job that reacts to changes to compass chart in Compass repository and create proper PR to Kyma repository.

**Comment by PK85** [comment]
not valid, closing
