### ISSUE TITLE
Update Application and Runtime status

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#839]
**Description**

Right now we Application and Runtime has status set to INITIAL. This ticket is about to update a status accordingly to real state of those entities.

**AC**
- director updates Application status to READY when first call from external Application was done
- director updates Runtime status to READY when first call from Runtime was done
- allow to update a status by IntegrationSystem/Application/Runtime/User

**Details**
Right now statuses:

```
enum RuntimeStatusCondition {
	INITIAL
	READY
	FAILED
}
enum ApplicationStatusCondition {
	INITIAL
	UNKNOWN
	READY
	FAILED
}
```
proposal statuses:
```
enum RuntimeStatusCondition {
	INITIAL
	CONNECTED
        FAILED
}
enum ApplicationStatusCondition {
	INITIAL
	CONNECTED
        FAILED
}
```

**Comment by crabtree** [comment]
@PK85 as I can see you added another AC fot the issue, saying that we need to allow to update the status by the IntegrationSystem/Application/Runtime/User. Can you elaborate a bit more on that? How should it work, when previously, we assumed that the Director will compute the status based on the actual Application/Runtime activity.

**Comment by crabtree** [comment]
As discussed with @PK85 we go with:

1. Change the available statuses for Application and Runtime to the following list:
- Initial - status used when the new entity is created
- Connected - should be set manually via the appropriate mutation
2. Align mutation for creating Application and Runtime to support optional status property, if not specified will be set to Initial
3. Align mutations for updating Application and Runtime to support optional property for a status update

The statuses will have informational purpouse.

In the next iteration the status will be automatically set to connected when the Runtime/Application communicates with the Director API. The communication can be direct or through the Integration System. 

Calls done by the user will not modify the status.
