### ISSUE TITLE
GQL client doesn't allow to send slash in label name

### ISSUE THREAD

**Issue by polskikiel** [kyma-incubator/compass#845]
**Description**

We use Provisioner's ProvisionRuntime mutation to create a runtime that allows us to send labels.
In the runtime agent, we use a pattern for labels keys `prefix/key`, to apply that we would like to set labels on runtime:
- **broker/instance_id**
- **global/subaccount_id**

unfortunately, the graphql client doesn't allow to send special characters like `- / :` as a parameter name.

**Expected result**

We have labels pattern which can be applied using the ProvisionRuntime mutation.

**Actual result**

Providing labels with a slash doesn't work. KEB would need to follow the pattern from runtime agent and label the runtime after it's provisioned.

**Steps to reproduce**

Try to send labels using the ProvisionRuntime mutation using the gql playground:
![image](https://user-images.githubusercontent.com/21159554/74532538-bc558580-4f2f-11ea-81ba-18ca4c6a67a2.png)

**Comment by pkosiec** [comment]
Looks like a bug indeed, because of GraphQL limits for special characters in field keys. In the meantime you can use `setRuntimeLabel` mutations to set your labels.

**Comment by polskikiel** [comment]
@pkosiec We don't want to do that because KEB doesn't know if the runtime was registered in the Director and it may lead to errors. We also need these runtimes labeled just after it starts to provision.

**Comment by polskikiel** [comment]
We can work around that issue by using different label keys without slashes and change it after it will be implemented. So it'd be:
- **broker_instance_id**
- **global_subaccount_id**

**Comment by Szymongib** [comment]
It is not possible in Director itself so I guess it is not an issue for the Provisioner.

**Comment by pkosiec** [comment]
Yup, the problem is in Director.

**Comment by kfurgol** [comment]
We decided to change the contract on labels.
 Label keys now will accept only alphanumeric symbols and an underscore. 

New AC: 
- Change validation of label keys to support only alphanumeric symbols and an underscore. 
- Check if any component(eg. Provisioner) which is using Director API is compliant with this change, make necessary changes if needed in those components and tests
- Notify dependant teams
