### ISSUE TITLE
Make API Definition name unique in API Package context

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/compass#883]
**Description**

API Definition names can be duplicated in the single API Package scope. We would like to have unique API names inside a single Package.

**Reasons**

In the new approach of creating Service Instances (SI for API package), we want the user to easily differentiate between registered APIs. 
API already has a unique ID but it is not very user-friendly, therefore we would like to depend on API names as a way for the user to differentiate between APIs.

**Comment by PK85** [comment]
we need to rethink the whole name/displayName and ids story, closing for now
