### ISSUE TITLE
Compass Provisioner - Kyma installation hangs on Tiller on Azure

### ISSUE THREAD

**Issue by ksputo** [kyma-incubator/compass#889]
**Description**
Compass provisioner has stabillity issues with Kyma installation on Azure platform. This bug is particularly problematic, as it seems that cluster in this state will not be deprovisioned (as it hangs in 'in progress' operation state and provisioner does not allow that) and  **will never reach Kyma timeout installation** - I still have a runtime which is in that endless loop for 2 days straight.

Please DM me if you need the access to broken runtimes to investigate the problem.

**Expected result**
Kyma installation is triggered and starts installing Kyma components.

**Actual result**
Kyma installation do not start at all - instead it hangs with error and goes into endless loop:
```
time="2020-02-28T10:21:56Z" level=error msg="Error triggering Kyma installation: failed to trigger installation: Failed to prepare installation: failed to apply Tiller resources: failed to apply resource: failed to create object tiller of kind ServiceAccount: serviceaccounts \"tiller\" already exists" Component=ShootReconciler OperationId=caae32c1-105c-4d94-a08b-f0e6f0b6536c Shoot=garden-kyma-dev/azu-5ce5e76
```

**Steps to reproduce**
Not easy to reproduce as it seems it happens randomly, however during testing e2e flow it happened 3 times over around 15 trials, all on Azure. Just try to provision a runtime on azure and sooner or later it will happen. Complete logs from provisioner, look for logs for operation ID `88eba02b-8f23-41c9-a995-449922b0a66e` :

[azure-log-fail-tiller.log](https://github.com/kyma-incubator/compass/files/4266606/azure-log-fail-tiller.log)

**Troubleshooting**
Discussed possibilities with Framefrog team - one idea is to extend the Tiller installation timeout.

**Comment by janmedrek** [comment]
The error returned is:
`failed to create object tiller of kind ServiceAccount: serviceaccounts \"tiller\" already exists`

Is it something that will be handled by extending the timeout? Does not seem like a solution to me - it will fail endlessly since it conflicts on ServiceAccount creation. Perhaps some kind of upsert would be the way to go?

**Comment by janmedrek** [comment]
Solved in: https://github.com/kyma-incubator/compass/pull/899
