### ISSUE TITLE
Labels in Application Template work only with array values

### ISSUE THREAD

**Issue by tgorgol** [kyma-incubator/compass#904]
**Description**
When creating Application Template with Label that has value type different than array, Director can't convert the model to graphql string to return created entity.

**Expected result**
Application Template should be created successfully and returned in the response.

**Actual result**
```
{
  "errors": [
    {
      "message": "while converting application template to graphql: while graphqlising application create input: while graphqlising application create input: while executing template: template: tmpl:10:13: executing \"tmpl\" at <LabelsToGQL .Labels>: error calling LabelsToGQL: while executing template: template: tmpl:4:23: executing \"tmpl\" at <$v>: range can't iterate over true",
      "path": [
        "createApplicationTemplate"
      ]
    }
  ],
  "data": null
}
```

**Steps to reproduce**
Try creating following Application Template:
```graphql
  createApplicationTemplate(in: {
    name: "example-app-template"
    accessLevel: GLOBAL
    applicationInput: {
      name: "example-app"
      labels: {
      	bug: true
    	}
    }
  }) {
    applicationInput
  }
```

**Troubleshooting**
Looks like the bug is in `graphqlizer.go` file, `LabelsToGQL` function expects the label value to alway be an array. It shouldn't.

**Comment by PK85** [comment]
fixed, closing
