### ISSUE TITLE
Provisioner creates Gardener as many worker groups as desired nodes

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/compass#932]
**Description**

Provisioner API creates too big clusters in Gardener. The input parameter Node Count is used to create worker groups. With nodeCount = 3 and autoScalerMin = 2 you will get the cluster with 6 nodes.
It happens because provisioner creates as many worker groups as nodeCount and each group has number of machines specified in autoscaler settings.

**Expected result**

1 worker group is created.

**Actual result**

Too many worker groups are created

**Links**
- [Worker group spec](https://gardener.cloud/api-reference/core/#core.gardener.cloud/v1beta1.Worker)
- [Code that creates worker groups](https://github.com/kyma-incubator/compass/blob/7c486b4e41d724f6b9945f39148dc6454ce2b669/components/provisioner/internal/model/gardener_config.go#L187-L190)

**Comment by mszostok** [comment]
Currently, we change the KEB behavior to send `nodeCount=1` because the nodeCount is required. If you will fix that on your side please remove also sending the `nodeCount` from KEB source code:

https://github.com/kyma-incubator/compass/pull/934/files#diff-3b004e25742ce2ba4a362869881893e9R79
