### ISSUE TITLE
Tag Azure Resource Group and Event-hub namespace created via Kyma Environment Broker

### ISSUE THREAD

**Issue by anishj0shi** [kyma-incubator/compass#967]
In Real time, there has to be a correlation between the name of a provisioned kyma-runtime and the resource group and namespaces created in Azure for the event-hubs. 

**AC** 
- Figure out a way to evaluate the name of kyma-runtime (which is dynimic in nature) or runtime id (timebox it to 1 day)
- Use the above name, instance ID, the subaccount id and operation ID provided as provisioning parameter to tag the created resource group and namespace

**Comment by marcobebway** [comment]
The following Azure tags are applied to the resource group and namespace:

- SubAccountID
- InstanceID
- OperationID

At the moment the dynamic name of the Kyma runtime is not available.

**Comment by marcobebway** [comment]
The following tags are applied to the Azure Resource Group and EventHubs namespace:

- SubAccountID
- InstanceID
- OperationID

At the moment the dynamic name of the Kyma runtime is not available.
