### ISSUE TITLE
Create an Azure Event-hub instance in the same location as the provisioned kyma-runtime

### ISSUE THREAD

**Issue by anishj0shi** [kyma-incubator/compass#968]
while creating a service instance in the Kyma Environment Broker, we need to propagate azure's region from the provisioning parameter to the event-hub namespace provisioning step.  as the event-hub namespace has to semantically in the same region to that of provisioned kyma-runtime

**Comment by anishj0shi** [comment]
@k15r  you probably have to be careful in propagating Region from provisioning parameter directly, as it might have regions which are not acceptable regions for azure.

**Comment by k15r** [comment]
well then i guess we need a mapping from 'unacceptable' => 'acceptable'
Who would provide this mapping?

**Comment by anishj0shi** [comment]
As other cloud providers are not supported right now, it just makes sense to validate the request with azure's region list. Having a 1:1 mapping seems unrealistic and almost impossible to maintain.
