### ISSUE TITLE
Fix compass database

### ISSUE THREAD

**Issue by polskikiel** [kyma-incubator/compass#998]
**Description**

The main issue: https://github.com/kyma-incubator/compass/issues/688. It fails first connections to the database for all compass components:
- KEB
- Director
- Provisioner
- ORY Hydra

It occurs on both embedded and cloud DB.

Example error on Hydra:
![image](https://user-images.githubusercontent.com/21159554/77153558-3d0d2180-6a9a-11ea-9661-d2f0b663a5e1.png)

Ideas:
- Replace DB library with `gorm` or `github.com/jackc/pgx/v4/stdlib` or any other lib which can fix this issue
- configure SetMaxConnLifetime 
- Issue with connectivity

**Expected result**

The issue described here https://github.com/kyma-incubator/compass/issues/688#issuecomment-576626243 doesn't occur.

**Steps to reproduce**

Wait a few minutes since last call and send a request to KEB.

**Related issues**

https://github.com/kyma-incubator/compass/issues/960

**Comment by piotrmiskiewicz** [comment]
We need to set also SetMaxIdleConns and SetMaxOpenConns.

**Comment by piotrmiskiewicz** [comment]
SetMaxConnLifetime described: https://github.com/go-sql-driver/mysql/issues/529#issuecomment-290032952

**Comment by PK85** [comment]
Closing. Not valid anymore.
