### ISSUE TITLE
Run tenant loader only once

### ISSUE THREAD

**Issue by PK85** [kyma-incubator/compass#999]
**Description**
Current implementation of Tenant Loader marks all tenants that don't come from the list as inactive. That's incorrect. Tenant loader must  to add tenants from the list, only ONCE. Doesn't make sense to run loader every upgrade on compass.

**Reason**
Running tenant loader for every compass upgrade doesn't make sense and causes tenant inconsistency over time (initial tenant list is getting old). More or less we need to upload tenant list once, that could be manual step. We need current solution (cronjob, job) to be a tool that operators can use to upload tenants.

**AC**
- Enable Loader as a tool to be executed manually. Run every upgrade must be removed.
- Loader must just create all tenants from external and build-on list
- Execute job only during Compass installation
- Loader do not mark tenants as inactive (marking as inactive functionality will be removed from MP)
- fetcher works as before
- test new loader with DEV env. Make sure to change a externaltenants to true
- Modify existing tenant loader job to be related only to .Values.global.tenantConfig.useDefaultTenants override, so it's still easy to make kyma install with default tenants (default tenants will be added on every upgrade if the override is set)

**Examples**
- new initial list of tenants provided to operator. Operator runs a tool manually and new tenants are created.
- new default tenant added. Automatically created by director (for non-production usage)

**Comment by PK85** [comment]
Ticket needs to be reestimated. Previous estimation was 3SP.

**Comment by tgorgol** [comment]
With the new AC added:
> Enable Loader as a tool to be executed manually. Run every upgrade must be removed.

The proposed solution is:
1. Make tenant loader only ADD new tenants (not DELETE)
2. Modify existing tenant loader job to be related only to `.Values.global.tenantConfig.useDefaultTenants` override, so it's still easy to make kyma install with default tenants (default tenants will be still added on every upgrade if the override is set)
3. Create new CronJob with `suspend: true` in spec, so it will never be started automatically. This CronJob would be related only to `.Values.global.tenantConfig.useExternalTenants` override, and will only be responsible for loading tenants from provided config map.

With this solution, the flow for adding new tenants from a list of tenants would be following:
1. Manually create config map (with correct name, set in CronJob definition), that will contain external tenants, on cluster.
2. Use `kubectl create job --from=cronjob/<cronjob-name> <job-name>` command to manually create a job that's based on CronJob installed with the chart. That will result in single execution of tenant loader.
3. After successfully adding new tenants, manually delete previously created config map containing the list of tenants to add.
